### ISSUE TITLE
Boost build fails

### ISSUE THREAD

**Issue by onodera-punpun** [kisslinux/community#1023]
```
-> boost Building package (2/4)
-> boost Extracting sources
-> boost Starting build
sed: unmatched '/'
-> boost Build failed
```

Seems like a trailing `/` is missing from the sed command.

**Comment by dylanaraps** [comment]
Maintainer: @cemkeylan 

(Please mention the maintainer so that they are notified.)

**Comment by cemkeylan** [comment]
I'm sorry about this, pushed a fix :+1:
