### ISSUE TITLE
Build failure for xssstate

### ISSUE THREAD

**Issue by FriendlyNeighborhoodShane** [kisslinux/community#1053]
Maintainer: @xzcvczx

Build fails with missing header X11/extensions/scrnsaver.h, logs: ix.io/2rRl

I have xorg-server installed and working, does it need some other dependency?

**Comment by xzcvczx** [comment]
yes sorry libXScrnSaver, will do a pr in a couple of hours to add depends

**Comment by FriendlyNeighborhoodShane** [comment]
Thanks!

**Comment by dylanaraps** [comment]
Ping @xzcvczx

**Comment by FriendlyNeighborhoodShane** [comment]
That's cool with me. Looks like a 0-maintainance package right now :P

**Comment by FriendlyNeighborhoodShane** [comment]
Closed. Thanks me!
