### ISSUE TITLE
Python modules: naming?

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/community#1054]
I want to add qutebrowser and its dependencies to community. You can see what I want to add [here](https://github.com/sdsddsd1/kiss-s3d4).  
However, I struggle with the naming for `pyqt5` `py-qt5-webengine` and `py-sip`. I have tested with kiss-outdated and the search on repology itself and the naming must be `python:pyqt5` `python:sip` and for consistency `python:pyqtwebengine`. This is pretty out of line to all other packages.
I believe to remember that python-modules should be avoided in community, so I have added the necessary small ones in the qutebrowser package itself. So this is also a question if qutebrowser is suiteable to add at all.

**Comment by dylanaraps** [comment]
I like the way you have packaged this! With the way you have done it, I have no problems seeing it accepted into Community. I'd just double check that the `py-` packages are correctly named. :+1:
