### ISSUE TITLE
Build failed for neovim

### ISSUE THREAD

**Issue by axpira** [kisslinux/community#1090]
[neovim-2020-07-29-13:12-5546.log](https://github.com/kisslinux/community/files/4996074/neovim-2020-07-29-13.12-5546.log)
=== configuring in doc (/root/.cache/kiss/build-5546/neovim/.deps/build/src/gperf/doc)
configure: running /bin/sh ./configure --disable-option-checking '--prefix=/root/.cache/kiss/build-5546/neovim/.deps/usr'  'MAKE=/usr/bin/make' 'CC=/usr/bin/cc' 'CXX=/usr/bin/c++' 'LD=/usr/bin/cc' --cache-file=/dev/null --srcdir=.
checking whether /usr/bin/make sets $(MAKE)... yes
checking for a BSD compatible install... /usr/bin/install -c
configure: creating ./config.status
config.status: creating Makefile
ninja: subcommand failed
make: *** [Makefile:101: deps] Error 1

maintainer: @ioraff  Owen Rafferty <owenr@fferty.me>

**Comment by ioraff** [comment]
@dylanaraps has since taken over maintenance of this package.

**Comment by dylanaraps** [comment]
The error itself:

 ```sh
[23/89] Performing configure step for 'libvterm'
ninja: job failed: cd /tmp/build-2926/neovim/.deps/build/src/libvterm && "" "" && /usr/bin/cmake -E touch /tmp/build-2926/neovim/.deps/build/src/libvterm-stamp/libvterm-configure
/bin/sh: : Permission denied
```

**Comment by dylanaraps** [comment]
It's trying to execute a command which is... nothing ` "" ""`. This causes the "permission denied" error.

**Comment by dylanaraps** [comment]
This is generated by the build system : ```
build build/src/libvterm-stamp/libvterm-configure: CUSTOM_COMMAND build/tmp/libvterm-cfgcmd.txt build/src/libvterm-stamp/libvterm-update build/src/libvterm-stamp/libvterm-patch
  COMMAND = cd /tmp/build-4767/neovim/.deps/build/src/libvterm && "" "" && /usr/bin/cmake -E touch /tmp/build-4767/neovim/.deps/build/src/libvterm-stamp/libvterm-configure
  DESC = Performing configure step for 'libvterm'
  restat = 1
```

**Comment by dylanaraps** [comment]
OK. Turns out this is caused by newer versions of CMake. Will push the fix shortly.

**Comment by dylanaraps** [comment]
https://github.com/neovim/neovim/pull/12676
