### ISSUE TITLE
qt5-webengine: build failure because of bison 3.7

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/community#1096]
@dilyn-corner 
Qt5-webengine fails to build with the following. I have produced this error on 2 indepented KISS instalations...ohoh.
```
/tmp/build-1507/qt5-webengine/src/core/release/gen/third_party/blink/renderer/core/xpath_grammar.cc:124:10: fatal error: xpath_grammar.hh: No such file or directory
  124 | #include "xpath_grammar.hh"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: subcommand failed
```

Edit: Ah nice, this seems to be an error with bison 3.7 [gentoo bug](https://bugs.gentoo.org/734356)
Edit2: Theres also a missing dependency for `perl`
Edit3: Qt related: My falkon runs fine without `qt5-x11-extras`, is it really needed?
Edit4: `bison 3.7.1` does not resolve this issue.

**Comment by sdsddsd1** [comment]
The bug was reported at Qt upstream. [click](https://bugreports.qt.io/projects/QTBUG/issues/QTBUG-85835?filter=allissues).  
The patch provided there works for me in this sed:
`sed -i '/os.unlink(outputHTmp)/d' src/3rdparty/chromium/third_party/blink/renderer/build/scripts/rule_bison.py
`

**Comment by dilyn-corner** [comment]
Thanks for pointing all these things out - I've been on vacation, but I'll start looking into all these things and pushing changes tomorrow!

**Comment by dilyn-corner** [comment]
What I've found: 
`qt5-webengine` does in fact fail to build, and adding the provided sed line does indeed fix it.
`qt5-webengine` does not seem to require `perl` to build? Although `qt5-x11extras` does. I've added it.

`falkon` definitely fails to both build AND run without `qt5-x11extras` installed, on my end at least. At the very least it's a make dependency, and `falkon` seems to link to some libraries `qt5-x11extras` provides, making it a runtime dep.

**Comment by sdsddsd1** [comment]
My build of `qt5-webengine` failed very far in the build because of missing `perl`.  
Falkon: I am running X11 but I had without knowing forked the `falkon` package with the option `-DNO_X11=ON`.
It runs just fine. Funny.

**Comment by dilyn-corner** [comment]
OF COURSE the failure would happen near the end. Why wouldn't it. I'll set it up right now and I'll know in a few hours, then. Although nowhere else seems to list perl as a make dependency for it, we will know soon enough. 

I wonder then what `falkon` uses those libs for. I'll have to look into it and see.

**Comment by sdsddsd1** [comment]
I will test the falkon modification on my KDE machine. I have some windowdecoration in mind.
