### ISSUE TITLE
gc cannot download source

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#1101]
Source fails to download due to SSL/CA cert issues. 

@trbednarzyk

**Comment by trbednarzyk** [comment]
Interestingly, only `curl` has this issue. I was able to download the file with `wget` without any issue. Firefox also doesn't seem to have this issue when browsing the site.

I could change the source from https://hboehm.info/gc/gc_source/ to https://github.com/ivmai/bdwgc to get around this issue.

Thoughts?

**Comment by dylanaraps** [comment]
If it's the same project :+1:
