### ISSUE TITLE
Adopt the whole GNU Stack and more...

### ISSUE THREAD

**Issue by a-schaefers** [kisslinux/community#1135]
So, this offer is all-or-nothing. I'll keep maintaining it if I have to, but I've been quite busy and it'd be nice if someone took this opportunity to maintain some serious KISS packages and lighten my load. Not looking to adopt out 1 or 2 packages. For whatever-it's-worth, this stack of software can even look good on a job resume, and was a part of my resume when I was applying for my first job in the field. It's good software, worth maintaining. Takes about 15 minutes a week once you get it down to a science.

```
bc
coreutils
dash
diffutils
ed
emacs
emacs-git
emacs-nox
findutils
gawk
gnu-netcat
gnugrep
gnupg2
gnutls
gtar
iproute2
iptables
iputils
kmod
libassuan
libcap
libgcrypt
libgpg-error
libksba
libxaw3d
lzip
lzo
mksh
nettle
npth
openvpn
patch
pciutils
pinentry
pkcs11-helper
procps-ng
readline
sed
shadow
strace
wget

```

**Comment by periish** [comment]
Oh my. I'll have to consider this.

**Comment by a-schaefers** [comment]
Last call before I release them to the wild

**Comment by Vouivre** [comment]
I need some of them, but at the moment I can't take all of them. I will rather take some of them after you have drop all those packages.
