### ISSUE TITLE
Replace readline with editline

### ISSUE THREAD

**Issue by periish** [kisslinux/community#1141]
[editline](https://github.com/troglobit/editline) is a smaller, more permissive replacement for `readline`, with a compatibility layer.
Furthermore, editline has no external dependencies; unlike readline, which has a dependency on ncurses.

The only packages which depend on readline are `ncmpcpp` and `pcre2`, maintained by @onodera-punpun. Readline itself is maintained by @a-schaefers.
I have an editline package in my personal repository, kiss-all/cmd-utils, and a package using it, byron's rc shell implementation, for those who may wish to try out editline.

**Comment by onodera-punpun** [comment]
I remember I using editline with ncmpcpp a year or so ago, and back then it would break the program. Not sure if this is still the case though, Just something to keep in mind.

**Comment by periish** [comment]
Seems like this issue is a bust then. Readline stays, as neither alternative seems to work as a replacement :/
