### ISSUE TITLE
sbase/ubase checksum mismatch

### ISSUE THREAD

**Issue by Necromantic-Ritual** [kisslinux/community#1175]
Hi, I'm getting a checksum mismatch when attempting to build both sbase/ubase.

`kiss b sbase`
`-> Resolving dependencies`
`-> Building: sbase`
`-> sbase Checking repository files`
`-> Checking for pre-built dependencies`
`-> sbase Downloading sources`
`-> sbase Found local relative source 'patches/tar-dash-remove.patch`
`-> sbase Checksum mismatch`
`ERROR Checksum mismatch with: sbase`

**Comment by dylanaraps** [comment]
Please mention the maintainer when submitting issues. 

```
=> /home/dylan/projects/community/community/sbase
Cem Keylan <cem@ckyln.com>
-> kiss-maintainer ubase
=> /home/dylan/projects/community/community/ubase
Cem Keylan <cem@ckyln.com>
```

@cemkeylan

**Comment by Necromantic-Ritual** [comment]
No worries, will do in the future.

**Comment by cemkeylan** [comment]
I don't have any issues, is this because of the checksums behaviour change
@dylanaraps ?

**Comment by dylanaraps** [comment]
@cemkeylan It could be related to that, yes. The only issue I see is that I explicitly tried to make this backwards (or forwards(?)) compatible.

**Comment by dylanaraps** [comment]
Will push a fix in a few minutes. :+1:

**Comment by cemkeylan** [comment]
When I am doing with upstream kiss, it says checksum mismatch, when I am doing with my fork it doesn't. I should update the checksums anyway.

**Comment by dylanaraps** [comment]
Fixed here: https://github.com/kisslinux/kiss/commit/3b251b96b6939895a2534b7a1e14efa613f0d288

**Comment by cemkeylan** [comment]
Okay, it works now, should I update the checksums regardless?

**Comment by dylanaraps** [comment]
No. It's fine. Pushed a new package manager release.

**Comment by dylanaraps** [comment]
If you decide to follow the same checksum changes, these checksums will over time match the new scheme whenever the checksums are updated. The KISS package manager supports both formats rather easily so there's no rush. I foresee us living in this transition period for some time. :+1:

The scheme is just: 

```
<checksum>
<checksum>
etc
```

- Git sources are skipped.
- Directory sources are skipped.
