### ISSUE TITLE
btrfs-progs missing dependency on pkgconf

### ISSUE THREAD

**Issue by glats** [kisslinux/community#1226]
After ran
 ```
$ kiss b btrfs-prog
```
Shows:
```
checking for reallocarray... no
checking for pkg-config... no
checking for EXT2FS... no
configure: error: in `/root/.cache/kiss/build-11726/btrfs-progs':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

Alternatively, you may set the environment variables EXT2FS_CFLAGS
and EXT2FS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

To get pkg-config, see <http://pkg-config.freedesktop.org/>.
See `config.log' for more details
```

I had to built manually 
```
$ kiss b pkgconf
...
$ kiss i pkgconf
```
Is it possible to declare it as a dependency?

Thannks!
PD: nice distro!

**Comment by dylanaraps** [comment]
Please mention the maintainer of the package when opening issues.

```
-> kiss-maintainer btrfs-progs
=> /home/dylan/projects/community/community/btrfs-progs
ax <ax@slackware.eu>
```

@aicsx

**Comment by aicsx** [comment]
yes It Is... but give me time for verification please. Thanks for report!

**Comment by aicsx** [comment]
I am forced to go back to what was previously stated.  I believe the build is correct and the dependencies are respected.  Honestly, I don't think it's necessary to add addiction.  I can of course do this, but it is not an addiction to solve your specific problem.  I await further instructions from dylan, as far as I'm concerned, he's fine.

**Comment by glats** [comment]
This problem occurred in the begin of the my installation. I followed all the steps and the only difference was i choose btrfs instead of ext4. So maybe I skipped some program that bring pkgconf as dependency and that was why btrfs-prog didn't find it.

**Comment by dylanaraps** [comment]
@aicsx Just add `pkgconf make` to the `depends` file.
