### ISSUE TITLE
Orphaning my packages

### ISSUE THREAD

**Issue by IslandAlpha** [kisslinux/community#1241]
it isn't feasible for me to use KISS as a daily driver anymore, so I'll be dropping packages I don't need.

- [x] jbig2dec @noocsharp (waiting on adoption pr)
- [x] lcms @Vouivre 
- [x] libmupdf @noocsharp 
- [x] openjpeg @noocsharp 
- [x] pash @dylanaraps 
- [x] tor @mmatongo 
- [x] wireguard-tools @GullikX 
- [x] zathura-pdf-mupdf @noocsharp 

I'll be keeping tcc; it's a really small and fast c99 compiler. I'm hoping to get around to making a core repo with tcc (or another minimal compiler) instead of gcc, eventually.

**Comment by dylanaraps** [comment]
I'll take pash .

**Comment by Vouivre** [comment]
I need lcms for cups-filters. So I will maintain it.

**Comment by GullikX** [comment]
I can take wireguard-tools.

**Comment by mmatongo** [comment]
I'll take `tor`

**Comment by noocsharp** [comment]
I need zathura-pdf-mupdf, so I'll take it, jbig2dec, libmupdf, and openjpeg.
