### ISSUE TITLE
pciutils: libpci.so.3 links to libpci.a instead of libpci.so.3.7.0

### ISSUE THREAD

**Issue by aosync** [kisslinux/community#1283]
On my system, libpci.so.3 symlinks to libpci.a instead of libpci.so.3.7.0.

Can you reproduce? @cemkeylan

**Comment by cemkeylan** [comment]
I cannot reproduce this. The output for the readlink call:

    $ readlink -f /usr/lib/libpci.so.3
    /usr/lib/libpci.so.3.7.0

However, the Makefile for pciutils is pretty junk, and if there is no
issue on your libpci.so.3.7.0 file, I can make the build script link the
shared library manually.

aosync writes:
