### ISSUE TITLE
seatd has dependencies on meson, samurai

### ISSUE THREAD

**Issue by dilyn-corner** [kisslinux/community#1287]
@muevoid; two make depends please :)

**Comment by muevoid** [comment]
Will do, will be at laptop later.

**Comment by konimex** [comment]
Just `meson` as the makedepend should be enough. `meson` has a dependency on `samurai`.

**Comment by dylanaraps** [comment]
Fixed here: https://github.com/kisslinux/community/commit/406fa31561a86074f5c2a9d408ce4676c9815e7e
