### ISSUE TITLE
aerc: missing manual page

### ISSUE THREAD

**Issue by cemkeylan** [kisslinux/community#1309]
There is a missing manual page on aerc, which is causing the build to fail.
The new manpage is aerc-stylesets.7

@icyphox

**Comment by dylanaraps** [comment]
Also... I don't think this should be a git package while also shipping static manual pages. Manual pages were added Jan 15, god knows how outdated they are by now lol. This should track releases and manual pages should be updated each time (unless other solution isn't found).

**Comment by eudaldgr** [comment]
That can help #1325.
Remove this [line](https://github.com/kisslinux/community/blob/6a4a21df05a7b5e2d66eadb19bee83c8a96432de/community/aerc/build#L3) and add a make depends.

**Comment by dylanaraps** [comment]
Icyphox has orphaned their packages. aerc is free to good home.

**Comment by eudaldgr** [comment]
PR made.
