### ISSUE TITLE
pkgconf is no longer an implicit dependency. some pkg's don't build without it.

### ISSUE THREAD

**Issue by eudaldgr** [kisslinux/community#1311]
`kmod` - @magenbluten 
~~`qemu` - @jedavies-dev~~
~~`libtorrent` - @jedavies-dev~~
~~`transmission` - @onodera-punpun~~ 
~~`girara` - @Vouivre~~
~~`zathura` - @Vouivre~~
~~`gnutls` - @cemkeylan~~
~~`glib-networking` - @cemkeylan~~
~~`libsoup` - @cemkeylan~~
~~`poppler` - @Vouivre~~
`xcb-util-xrm` - @alaughlin 
~~`alsa-plugins` - @onodera-punpun~~
~~`bind` - @aicsx~~
`conky` - @dzove855 
~~`cups-filters` - @Vouivre~~
~~`picom` - @konimex~~
~~`w3m` - @trbednarzyk~~

**Comment by Vouivre** [comment]
I will update my packages in the following days. I began with `cups-filters`, but it doesn't build anymore. I will first fix it.

**Comment by Vouivre** [comment]
@eudaldgr How did you get this list of packages for which `pkgconf` is missing ? 

For the future, if I create a new package, it's possible that I miss this dependency because it's installed by another package. I only see two solutions:

- check the build dependencies in the documentation of the software
- uninstall pkgconf and test the build

But to check for a lot of packages, I expect another method.

**Comment by eudaldgr** [comment]
I have a chroot with all the main repo pkg's installed, since a lot of time for diferent purposes.
On my machine i do a remove orphans regularly, and `pkgconf` is only needed at build time, so when i see i can't install `kmod` and later update `qemu`, i take that chroot, removed `pkgconf` package and tried to install all community pkg's.

That list is not completed i do a part of the community repo only.

So, yes 'uninstall pkgconf and test the build'

**Comment by Vouivre** [comment]
Thank you for your answer! All my packages are updated now and I will check this dependency in the future.

**Comment by dylanaraps** [comment]
Made the remaining changes. Thanks everyone.

**Comment by eudaldgr** [comment]
The list are not exhaustive, maybe there is more out there, but thanks!

**Comment by dylanaraps** [comment]
Yeah... There are two options here:

1. `kiss r pkgconf` -> try to build everything in Community.
2. Wait until bug reports are opened by users.
