### ISSUE TITLE
[tracker] Outdated packages.

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#1314]
Outdated packages has been sitting at around 30~ for a while now. Some of these packages are of more importance than others. If issues are preventing the update of packages or you do not have the time to maintain them, let me know and I'll assist you. I'm 
also happy to take over maintenance for those unable to do so in the short to long term. Just let me know. :+1: 

I've added notes for length outdated for the more extreme cases. 

- [x] bind 
    - Maintainer: @aicsx 
    - We're following a development release rather than stable. We should be on: 9.16.7, not 9.17.X.
    - Package is outdated regardless.

> BIND 9.17 is an unstable development release of BIND. This document summarizes new features and functional changes that have been introduced on this branch. With each development release leading up to the stable BIND 9.18 release, this document will be updated with additional features added and bugs fixed. Please see the CHANGES file for a more detailed list of changes and bug fixes.

- [x] bitfetch
    - Maintainer: @bit9tream 
    - Outdated for 3 months.

- [x] conky
    - Maintainer: @dzove855 
    - Outdated since end of July.

- [x] dash
    - Mantainer: @periish 
    - Outdated for one month.

- [x] fet.sh
    - Maintainer: @aosync 

- [x] fzf
    - Maintaner: @periish 

- [x] gnugrep
    - Maintainer: @periish 
    - New version released today? https://savannah.gnu.org/forum/forum.php?forum_id=9820

- [x] kakoune
    - Maintainer: @Jackojc 
    - Last updated in January but two(?) releases since.

- [x] libuv
    - Maintainer: @aicsx 
    - Outdated since July.

- [x] links2
    - Maintainer: @electimon 
 
- [x] mblaze
    - Maintainer: @ectlunya 
    - https://github.com/leahneukirchen/mblaze/releases/tag/v1.0

- [x] nnn
    - Maintaner: @lieuxnoir 

- [x] osh
    - Maintainer: @jedahan 
    - Stuck on pre-release?

- [x] radare2
    - Maintainer: @icyphox 
    - Outdated since July 17

- [x] strace
    - Maintainer: @magenbluten 

Some other packages have incorrect versions, etc. Will open separate issues for these. Thanks everyone.

**Comment by onodera-punpun** [comment]
repology reports dolphin-emu `5.0.12247` as being outdated, however this is the latest stable release. The versions it reports as up-to-date are wrong; `5.0` is very old, and `5.0.12595` is a development release.

**Comment by dylanaraps** [comment]
Yeah @onodera-punpun, this is why I didn't add dolphin-emu to the list (or tag you). :+1:

**Comment by Jackojc** [comment]
Submitted a PR for Kakoune. #1328

**Comment by electimon** [comment]
Submitted PR for links2 :) #1331

**Comment by noocsharp** [comment]
Given that @periish appears to be AWOL (#1165), I'd be happy to take over dash.

**Comment by periish** [comment]
Hello! I’ve been gone for a little due to the restart of my education. I should be able to upgrade my packages by Friday.

**Comment by periish** [comment]
I’ll be back soon; a personal, kiss-related project, has been a time muncher alongside my education.

**Comment by icyphox** [comment]
Hey, I no longer use KISS as my primary distro and haven't the time to
maintain any packages.  All packages under me are up for maintainership
and/or removal from the repos.

Apologies for not having done this sooner.

--
Anirudh Oppiliappan
https://icyphox.sh

**Comment by periish** [comment]
Cem seems to have updated gnugrep for me, mistakenly. 1334 is my PR.

**Comment by Jackojc** [comment]
Could you cross kakoune off the list @dylanaraps ?

**Comment by dylanaraps** [comment]
@periish Feel free to take over gnugrep once again. You could also leave it to Cem, it's up to you.

**Comment by periish** [comment]
I think I'll take over gnugrep. Could you cross the now updated packages off?

**Comment by eudaldgr** [comment]
Submited a PR for `radare2` #1349

**Comment by aicsx** [comment]
Sorry for the delay, I'm sorry to report that the problem is not the difficulty in build out.  Given that I have chosen to use the devel version because it works properly unlike the stable with which I had many problems, having said that, I cannot guarantee the update of always updated packages in guaranteed times.  I have serious health problems in "my brother" family and I am dealing with this day and night.  If there is a moral need to necessarily update things that work to 100% then I authorize "dylan" to take charge of btrfs and libuv. Sorry but my system is stable as it is and at the moment I have more urgent matter which requires my time. in faith.

**Comment by dylanaraps** [comment]
@aicsx Take all the time you need.

**Comment by dylanaraps** [comment]
NSS is free to any takers. Has been out-of-date since July 24. It's needed for qt5-webengine so may be of interest to @dilyn-corner. Context: https://github.com/kisslinux/community/issues/1165#issuecomment-699626418

**Comment by dilyn-corner** [comment]
I'm more than happy to maintain this horrifyingly abysmal package :) PR incoming.

**Comment by Vouivre** [comment]
Hello, I want to test `nnn`. It's not the first time, but I could use it more often now. so I have to update the package. I can update to the new version if you want to. If I keep it, I could maintain it if it's ok for @lieuxnoir .

**Comment by dylanaraps** [comment]
Thanks everyone.
