### ISSUE TITLE
webkit2gtk build fails

### ISSUE THREAD

**Issue by cemkeylan** [kisslinux/community#1318]
I am the maintainer, so no need to tag anyone.

Many users in the IRC, including me, reported that webkit2gtk build fails.
Since I already had the latest version built and installed already, I believe
that this is an issue related to another package that was updated/changed
after the latest webkit2gtk PR #1294 .

**Comment by cemkeylan** [comment]
@muevoid, @sdsddsd1, and @mcpcpc are having these issues, so I am tagging you as well.

**Comment by muevoid** [comment]
I fixed this issue with the following:

```
sed -i '239,244d' Source/WebKit/WebProcess/InjectedBundle/Injected
Bundle.cpp
```

**Comment by sdsddsd1** [comment]
With muevoid's fix, the package builds on my end.

**Comment by cemkeylan** [comment]
Thank you @muevoid

**Comment by muevoid** [comment]
Np
