### ISSUE TITLE
Python packages requiring rebuilds

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#1355]
Send a PR bumping the second field in the version file. 

- [x] asciinema @mmatongo 
- [x] py-sip @sdsddsd1 
- [x] pyqt5 @sdsddsd1 
- [x] pyqtwebengine @sdsddsd1 
- [x] qemu @jedavies-dev 
- [x] qutebrowser @sdsddsd1 
- [x] youtube-dl @Vouivre 

These packages require rebuild for Python 3.9.

**Comment by mmatongo** [comment]
Done

**Comment by dylanaraps** [comment]
Thanks everyone.
