### ISSUE TITLE
Dropping my packages

### ISSUE THREAD

**Issue by periish** [kisslinux/community#1427]
- [ ] baseutils
- [x] bc @onodera-punpun 
- [ ] custard
- [x] dash-shell @noocsharp 
- [x] ed @dylanaraps
- [x] fzf @Vouivre 
- [ ] gauche
- [ ] lux
- [x] lzip @dylanaraps 
- [ ] mg
- [x] patch @dylanaraps 
- [x] readline @onodera-punpun 
- [ ] wmutils

**Comment by noocsharp** [comment]
I'll take dash

**Comment by periish** [comment]
Send in your PR, and it’s yours.

**Comment by onodera-punpun** [comment]
I'll take `readline`

**Comment by onodera-punpun** [comment]
Oh, and `bc`.

**Comment by Vouivre** [comment]
Sorry, I referenced the wrong issue.....

**Comment by dylanaraps** [comment]
I'll take lzip and patch.

**Comment by Vouivre** [comment]
I take `fzf`.

**Comment by dylanaraps** [comment]
Dropped the remaining packages. Resubmit them if you'd like to adopt them. Thanks everyone.
