### ISSUE TITLE
Dropping packages

### ISSUE THREAD

**Issue by cemkeylan** [kisslinux/community#1429]
These are all of my packages, send a PR if you want to have any, and link this
issue so I will be notified and mark them complete.

- [x] ~~9base~~ @dylanaraps 
- [x] ~~bkeymaps~~ @dylanaraps 
- [x] ~boost~ @onodera-punpun 
- [x] ~~coreutils~~ @dylanaraps 
- [x] ~~diffutils~~ @dylanaraps 
- [x] ~~discount~~ @dylanaraps 
- [x] ~~distcc~~ dropped from community
- [x] ~~emacs~~ @Vouivre 
- [x] ~~emacs-nox~~ dropped from community
- [x] ~~emacs-git~~ dropped from community
- [x] ~~gawk~~ @dylanaraps 
- [x] ~~glib-networking~~ @muevoid 
- [x] ~~gnupg2~~ @muevoid 
- [x] ~~gnutls~~ @muevoid 
- [x] ~gnugrep~ @onodera-punpun 
- [x] ~~groff~~ @trbednarzyk 
- [x] ~~gstreamer~~ @sdsddsd1 
- [x] ~~gst-plugins-base~~ @sdsddsd1 
- [x] ~~gst-plugins~~ @sdsddsd1 
- [x] ~~harfbuzz-icu~~ @muevoid 
- [x] ~~icu~~ @muevoid 
- [x] ~~isync~~ dropped from community
- [x] ~~libassuan~~ @muevoid 
- [x] ~~libedit~~ dropped from community
- [x] ~~libgcrypt~~ @muevoid 
- [x] ~~libgpg-error~~ @muevoid 
- [x] ~~libksba~~ @muevoid 
- [x] ~libmpdclient~ @onodera-punpun 
- [x] ~~libpsl~~ @muevoid 
- [x] ~~libsoup~~ @muevoid 
- [x] ~~libxaw3d~~ @Vouivre 
- [x] ~~libxslt~~ @muevoid 
- [x] ~mpc~ @onodera-punpun 
- [x] ~mpd~ @onodera-punpun 
- [x] ~~nano~~ @dylanaraps 
- [x] ~~nettle~~ @muevoid 
- [x] ~nmap~ @Vouivre 
- [x] ~~npth~~ @muevoid 
- [x] ~~pandoc-bin~~ @dylanaraps 
- [x] ~~parted~~ @trbednarzyk 
- [x] ~~pciutils~~ @dylanaraps 
- [x] ~~pinentry~~ @muevoid 
- [x] ~~pinentry-dmenu~~ @Vouivre 
- [x] ~~procps-ng~~ @dylanaraps 
- [x] ~~ruby~~ @muevoid 
- [x] ~~runit~~ @dylanaraps 
- [x] ~~sbase~~ @dylanaraps 
- [x] ~~sent~~ dropped from community
- [x] ~~shinit~~ @dylanaraps 
- [x] ~~sic~~ dropped from community
- [x] ~~sinit~~ @dylanaraps 
- [x] ~~surfraw~~ dropped from community
- [x] ~sxiv~ @Vouivre 
- [x] ~sysmgr~ @dilyn-corner 
- [x] ~~tabbed~~ @Vouivre 
- [x] ~~ubase~~ @dylanaraps 
- [x] ~~uemacs~~ dropped from community
- [x] ~~vimb~~ dropped from community
- [x] ~~vimpc~~ dropped from community
- [x] ~~webkit2gtk~~ @muevoid 
- [x] ~~wget~~ @dylanaraps

**Comment by dilyn-corner** [comment]
I'd take `sysmgr`. There are several others I need but they're required by other things in community other people maintain.

**Comment by cemkeylan** [comment]
@dilyn-corner Great, just a heads up, I have switched to the C implementation for sysmgr which is on https://github.com/cemkeylan/sm . The old shell version still lives on the same repository.

**Comment by onodera-punpun** [comment]
I can take `mpc`, `mpd`, `libmpdclient`, `boost`, `gnugrep`.

**Comment by Vouivre** [comment]
For sure I use `sxiv`. I will think about adopting other packages.

**Comment by Vouivre** [comment]
I also adopt `nmap`.

**Comment by dilyn-corner** [comment]
Just to maybe speed this along...
@Vouivre: `gnutls` -> `msmtp`

@trbednarzyk: `groff` -> `graphviz`

@konimex: `libgpg-error` -> `libgcrypt` -> `irssi`

@ioraff: `pciutils` -> `flashrom`

@eudaldgr: `webkit2gtk` -> `surf`
@sdsddsd1: `webkit2gtk` -> `wyebadblock`
`webkit2gtk` also needs `glib-networking`, `icu` -> `harfbuzz-icu`, `libXslt`, `libgcrypt`, `libsoup`, `libwebp`, and `ruby`. 

I'll take `libXslt` because `qt5*` needs it, but I've built them just fine without it so I'd rather the new webkit maintainer takes it.

**Comment by trbednarzyk** [comment]
I can adopt `groff`, `libedit`, `parted`, and `pciutils`.

**Comment by eudaldgr** [comment]
If `webkit2gtk` fall i will maintain under my personal repo, i don't want to maintain more and more packages here.

**Comment by dylanaraps** [comment]
Reduced this list by half. Here's a crude listing of the remaining packages and their relationships with each other and other packages in community. In short: webkit2gtk and gnupg2 need most of what is waiting for adoption in the above list. These two also share a dependency or two (libgcrypt, libgpg-error, etc?). 

```
- surf, vimb, wyeb, wyebadblock
    - webkit2gtk
        - libsoup
            - glib-networking
                - gnutls
                    - nettle
            - libpsl
                - icu
            - gst-plugins ????
                - gst-plugins-base
        - gstreamer
            - gst-plugins
                - gst-plugins-base
        - harfbuzz-icu
            - icu
        - libgcrypt
            - libgpg-error
        - libXslt
        - ruby

- emacs, emacs-nox, emacs-git
    - gnutls
    - libxaw3d

- gnupg2
    - pinentry
        - libassuan
            - libgpg-error
    - libgcrypt
        - libgpg-error
    - libksba
    - npth

- pinentry-dmenu
- parted
- tabbed
- uemacs
- vimb

Other packages in Community which depend on these packages.

- msmtp
    - gnutls

- graphviz
    - groff

- qt5, qt5-webengine
    - libXslt
```

**Comment by sdsddsd1** [comment]
@dilyn-corner 
> `webkit2gtk` -> `wyebadblock`

I am not the right person to maintain this. When there are issues after a version change, I would probably not be able to fix this, until any other project had done this, which work I could adopt. Apologies.

**Comment by trbednarzyk** [comment]
@dylanaraps why did you drop `libedit` and adopt `parted` after I just adopted both?

**Comment by dilyn-corner** [comment]
Then maybe @muevoid has the time to work on `webkit2gtk`?

**Comment by muevoid** [comment]
Yes I do I can take everything left directly related to webkit2gtk minus vimb and gst-plugins and friends. Fyi afaik graphviz doesnt need groff.

**Comment by dylanaraps** [comment]
@trbednarzyk I must not have realized while going through the list, apologies. Just resubmit the packages.

**Comment by sdsddsd1** [comment]
I will take over 
- gstreamer
- gst-plugins
- gst-plugins-base

**Comment by Vouivre** [comment]
I'll have a look at emacs, tabbed and pinentry-dmenu. I could adopt them. It could take a few days.

**Comment by dylanaraps** [comment]
Only emacs stuff and vimb now. Thanks everyone. :)

**Comment by Vouivre** [comment]
If I adopt emacs, I won't adopt emacs-git. Is it ok for you ?

**Comment by dylanaraps** [comment]
That's fine. Do you use emacs? It's best that you adopt packages you have a vested interest in.

**Comment by Vouivre** [comment]
I still use it, but not a lot. For the moment it's better for me to have it in community.

**Comment by dylanaraps** [comment]
@Vouivre `libxaw3d` is a dependency of emacs, care to adopt it?

**Comment by Vouivre** [comment]
Of course! :+1:

**Comment by dylanaraps** [comment]
Thanks everyone
