### ISSUE TITLE
librsvg

### ISSUE THREAD

**Issue by a-schaefers** [kisslinux/community#144]
for #108 this is the one that I just can't get to compile without gettext or textinfo or whatever it is, if there are any wizards who could take a crack at it, I'd appreciate. Thanks

**Comment by dylanaraps** [comment]
You can use libsvg which is the older version written in C. It is being kept around and maintained for minimal/embedded systems and is 1:1 ABI compatible wit librsvg.

**Comment by a-schaefers** [comment]
ooh goodies

**Comment by a-schaefers** [comment]
I can't get emacs or libmagick6 to link against "libsvg" if you mean this one: https://www.cairographics.org/snapshots/libsvg-0.1.4.tar.gz which is looks to be old from 2005

**Comment by dylanaraps** [comment]
Either we use the outdated (and most likely insecure) C version or we go with Rust. :(

I'll work on fixing the rust builds.

**Comment by dylanaraps** [comment]
`librsvg` is gross huh. 

I can reproduce the issue you describe.

**Comment by a-schaefers** [comment]
indeed. I really need it too, because i use Emacs eww browser as my primary browser, and the damn browser breaks whenever i hit a page with svg. lol

**Comment by dylanaraps** [comment]
It has a long dependency list of GNOME libraries which are all mandatory. As well as mandatory Gettext etc. It's also written in Rust which complicates things.

I'll work on it.

Does Emacs' eww browser support any alternative SVG libraries by any chance?

**Comment by a-schaefers** [comment]
ill ask on #emacs irc but not that i know of

**Comment by dylanaraps** [comment]
Here's the last(?) C release of `librsvg`. It's out of date and no longer receiving updates/development but it should work regardless. It also has some security issues which we can probably patch, I just need to track down a CVE list from this time.

https://salsa.debian.org/gnome-team/librsvg-c

**Comment by dylanaraps** [comment]
Actually, here's the tarball link: https://ftp.gnome.org/pub/GNOME/sources/librsvg/2.40/librsvg-2.40.20.tar.xz

**Comment by a-schaefers** [comment]
> Actually, here's the tarball link: https://ftp.gnome.org/pub/GNOME/sources/librsvg/2.40/librsvg-2.40.20.tar.xz

Nice sleuthing.

Currently fails to build complaining "checking for gobject-introspection... configure: error: gobject-introspection-1.0 is not installed"
Quick google search turns up it probably wants this pkg https://www.archlinux.org/packages/extra/x86_64/gobject-introspection-runtime/files/ which looks to me like a dbus dependency. I tried searching for a configure flag to turn this off. Any ideas?

**Comment by a-schaefers** [comment]
For my purposes I am satisfied disabling svg's inside Emacs, to avoid running into svg bugs, atleast. Unless you're very motivated or an svg enthusiast I think we could just close this! (until someone comes along with a real need for it, it's convenient to drop. IMO)

**Comment by dylanaraps** [comment]
I'm happy to drop it too. :+1:
