### ISSUE TITLE
tree source link not available

### ISSUE THREAD

**Issue by mmatongo** [kisslinux/community#1442]
@aaronNGi the source link for tree needs to be updated, the https link is no longer accessible, the ftp link however is available: `ftp://mama.indstate.edu/linux/tree/tree-1.8.0.tgz`

**Comment by aaronNGi** [comment]
Hey. The http link in `sources` works for me. It's either on your end or was broken only momentarily.

**Comment by mmatongo** [comment]
It still won't work for me, I've tried it several times and on two different machines but still nothing.

**Comment by noocsharp** [comment]
I am able to download it, it's likely on your end.

**Comment by mmatongo** [comment]
It may be regional

**Comment by aaronNGi** [comment]
> It may be regional

Yeah, that must be the culprit.

It's inconvenient but you could download the source into `~/.cache/kiss/sources/tree/` manually for now or overlay the package and change the source to ftp.

**Comment by mmatongo** [comment]
I forked the package and did as advised, I suggested using the ftp link as to avoid this problem for anyone else in future.

**Comment by eudaldgr** [comment]
I don't remember where i read this, but i think that ftp is not recommended, instead of https, in kiss packages.

**Comment by mmatongo** [comment]
Unfortunately
