### ISSUE TITLE
parted: util-linux is a dependency

### ISSUE THREAD

**Issue by eudaldgr** [kisslinux/community#1450]
@cemkeylan

**Comment by cemkeylan** [comment]
See #1429

**Comment by eudaldgr** [comment]
I know, but if someone take it, she can fix this.

**Comment by eudaldgr** [comment]
I close this until someone take the pkg.

**Comment by dylanaraps** [comment]
Best we leave this open so we don't lose track of it.

**Comment by dylanaraps** [comment]
(It's also very much possible for the current maintainer to push a commit to fix this.)

**Comment by dylanaraps** [comment]
@trbednarzyk
