### ISSUE TITLE
Dropping some packages

### ISSUE THREAD

**Issue by eudaldgr** [kisslinux/community#1460]
* [x] ~~2bwm~~ @Vouivre 
* [x] ~~aerc~~ @muevoid 
* [x] ~~birch~~ - @dylanaraps 
* [x] ~~btpd~~ - @noocsharp 
* [x] ~~dejavu-ttf~~ @Vouivre 
* [x] ~~font-awesome-otf~~
* [x] ~~font-awesome-ttf~~
* [x] ~~hack~~ @dylanaraps 
* [x] ~~ledger~~ dropped from community
* [x] ~~libburn~~ @dylanaraps 
* [x] ~~libisoburn~~
* [x] ~~libisofs~~ @dylanaraps 
* [x] ~~radare2~~ dropped from community
* [x] ~~sc~~ @Xeno-Hypster 
* [x] ~~sc-im~~ @Vouivre 
* [x] ~~scdoc~~ @dylanaraps 
* [x] ~~shfm~~ @dylanaraps 
* [x] ~~squashfs-tools~~ @git-bruh 
* [x] ~~surf~~ @mcpcpc 
* [x] ~~svkbd~~ - @nikotidar 
* [x] ~~syslinux~~ dropped from community
* [x] ~~zzz~~ @dylanaraps ~~@onodera-punpun~~ ??

**Comment by dylanaraps** [comment]
I'll take birch and shfm (for obvious reasons) ;)

**Comment by mcpcpc** [comment]
I'll take surf

**Comment by onodera-punpun** [comment]
I'll take `zzz`

**Comment by Xeno-Hypster** [comment]
I'll be happy to take sc.

**Comment by noocsharp** [comment]
I can take btpd

**Comment by TAAPArthur** [comment]
I can take ledger and svkbd

**Comment by Vouivre** [comment]
I will adopt 2bm, sc-im and dejavu-ttf. Unfortunately there are some errors when I build sc-im and dejavu-ttf. I will first fix them.

**Comment by dylanaraps** [comment]
Build fix for dejavu-ttf:

```sh
#!/bin/sh -e

for file in ttf/*.ttf; do
    install -Dm644 "$file" "$1/usr/share/fonts/TTF/${file##*/}"
done
```

**Comment by dylanaraps** [comment]
Build fix for `sc-im`:

```sh
#!/bin/sh -e

export CFLAGS="$CFLAGS -fcommon"

make -C src
make -C src \
    DESTDIR="$1" \
    prefix=/usr \
    install
```

**Comment by dylanaraps** [comment]
@onodera-punpun Will you be sending a PR for `zzz`?

**Comment by Vouivre** [comment]
Thank you @dylanaraps , I got the problem with `dejavu-ttf`. I'll do `sc-im` later.

**Comment by Vouivre** [comment]
Done! Thank you for the fix for `sc-im` :+1:.

**Comment by dylanaraps** [comment]
Went ahead and adopted everything. Dropped some packages too. Send PRs if you'd like to adopt anything of mine from here. I don't mind. Thanks everyone. :)
