### ISSUE TITLE
youtube-dl new release (2020.11.01.1)

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#1488]
See: https://youtube-dl.org/

@Vouivre

**Comment by dylanaraps** [comment]
This is where development is currently located looks like: https://gitlab.com/dstftw/youtube-dl/-/commits/master

**Comment by Vouivre** [comment]
Thank you, I'll update it soon!

**Comment by dylanaraps** [comment]
https://github.com/kisslinux/community/commit/6980d4f1e45bd364ff03773eb780514d1972d5ea

**Comment by Vouivre** [comment]
I tested it with one video, it works for me. If the PR https://github.com/kisslinux/community/pull/1491 is ok for you, I let you close this issue. 

Thank you for your help :+1:
