### ISSUE TITLE
poppler-glib out of date

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#152]
Ping @tristelune1 

See: https://repology.org/projects/?inrepo=kiss_community&outdated=1

**Comment by tristelune1** [comment]
Done: [PR](https://github.com/kisslinux/community/pull/154).

By the way, how do you know when a software is updated ? I tried to write a script, but it seems there is something easier!

**Comment by dylanaraps** [comment]
I manually check Repology once a day though you could also easily script this through their API/scraping the web pages.

**Comment by tristelune1** [comment]
Thank you!
