### ISSUE TITLE
seatd: Package outdated

### ISSUE THREAD

**Issue by kennylevinsen** [kisslinux/community#1528]
0.4.0 was released on the 19th of October, and contains a decent list of fixes.

The announce mailing list is available here: https://lists.sr.ht/~kennylevinsen/seatd-announce.

@muevoid

**Comment by muevoid** [comment]
My bad I really need to make a script for when i update one of the packages i maintain in my repo so I can make a pr here I will open up a pr later today when I am at my pc(answering from my phone).

**Comment by dylanaraps** [comment]
@muevoid While you're at it, you have 5 other packages needing updates. https://repology.org/projects/?maintainer=38061852%2Bmuevoid%40users.noreply.github.com&inrepo=kiss_community&outdated=1

**Comment by muevoid** [comment]
@dylanaraps Yep my bad, I have all of those up to date other then icu(has issues still working on) just need to make a pr.

**Comment by kennylevinsen** [comment]
> My bad

No worries, just thought I'd notify as it seems like it might have been missed. :)
