### ISSUE TITLE
webkit2gtk fails to build with icu 68.1

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/community#1559]
@muevoid I have found a solution to build latest webkit with latest icu on the LFS handbook.
Already reproduced and works.

`echo 'add_compile_definitions("U_DEFINE_FALSE_AND_TRUE=1")' >> Source/WTF/wtf/CMakeLists.txt`

http://www.linuxfromscratch.org/blfs/view/svn/x/webkitgtk.html

**Comment by muevoid** [comment]
Will fix this today life has gotten the better of me for a few so I haven't had time to do stuff but will fix this now and bump packages.
