### ISSUE TITLE
Drawing: software with python dependencies

### ISSUE THREAD

**Issue by Vouivre** [kisslinux/community#158]
Hello,

Because of the problem I have with `gimp` I discovered the software `drawing`. I have created a package with the help of the developper. [Here is the issue](https://github.com/maoschanz/drawing/issues/153) I opened to package it. 

To use the software, python modules are needed. I can install the software on my computer without a problem. My question: how to package the python modules ? 

- I can install the python modules with `pip`, but then how to include them in the package ?
- or do I have to also package each python module ? 

What are the guidelines in that case ?

**Comment by dylanaraps** [comment]
These are probably best kept to your own repository. I'd really like to not see Community bloat up with an endless series of python- packages. The same goes for other software of the same nature.

Not everything needs to be a part of Community and I'd like to keep it somewhat focused. :+1:
