### ISSUE TITLE
libsndfile: Incorrect checksums

### ISSUE THREAD

**Issue by git-bruh** [kisslinux/community#1592]
@mcpcpc Build fails due to incorrect checksums

Correct sha256sum (Verified by downloading sources a few times):
`9df273302c4fa160567f412e10cc4f76666b66281e7ba48370fb544e87e4611a libsndfile-1.0.30.tar.bz2`

**Comment by mcpcpc** [comment]
see https://github.com/kisslinux/community/pull/1593
