### ISSUE TITLE
Dropping Packages

### ISSUE THREAD

**Issue by muevoid** [kisslinux/community#1597]
Maintaining mue-linux packages and having to make changes due to differences from kisslinux in addition to life recently makes me think I shouldn't have any packages here...

All my packages will live in my repo if any of them get dropped.

I am dropping all my packages in this repo here is a list:

- [x]  ~~Seatd~~ @dylanaraps 
- [ ] Webkit2Gtk
- [ ]  libsoup
- [ ] glib-networking
- [ ] gnutls
- [ ] nettle
- [ ] libpsl
- [ ] icu
- [ ] libgcrypt
- [ ] libgpg-error
- [ ] libXslt
- [ ] ruby
- [ ] gnupg2
- [ ] pinentry
- [ ] libassuan
- [ ] libksba
- [ ] npth

**Comment by sdsddsd1** [comment]
I will take webkit2gtk and related.

**Comment by dylanaraps** [comment]
I'll take seatd.

**Comment by sdsddsd1** [comment]
I will take 
- webkit2gtk
- libsoup
- glib-networking
- gnutls
- nettle
- libpsl
- icu
- libgcrypt
- libgpg-error
- libXslt
- ruby

**Comment by noocsharp** [comment]
I can take the gnupg2 stack
- gnupg2
- libksba
- libassuan
- npth
- pinentry

**Comment by dylanaraps** [comment]
@noocsharp Your PR is missing npth and pinentry??

**Comment by dylanaraps** [comment]
Thanks everyone!

**Comment by muevoid** [comment]
As @dylanaraps said thank you everyone sorry i couldn't maintain for longer. Main reason I am commenting though is I forgot one package aerc. If anyone would like to pick that up that is also up for grabs. Not sure if I should reopen or not so ill leave that up to dylan.
