### ISSUE TITLE
llvm: enable default targets

### ISSUE THREAD

**Issue by jedahan** [kisslinux/community#1623]
Some languages support cross compilation out-of-the-box by leveraging the default targets in llvm. As an example, I am packaging [zig](https://ziglang.org/). It is a core and expected feature of the language, to be able to create binaries for other architectures.

I am testing out a forked llvm where I just removed the specified TARGETS and used the defaults, and will report back if that works. If it does, I'd appreciate the same in the default build on llvm.

**Comment by mmatongo** [comment]
Hey, I am currently working on building [zig](https://ziglang.org/) for my languages repo [here](https://github.com/mmatongo/kiss-lang).

I worked with the bootstrap repo of `zig`, an upstream bug needs to be opened [as suggested here](https://github.com/ziglang/zig/issues/7209) to make it so you can build `zig` with no modifications to `llvm`


Also this should have been opened on the `kisslinux/repo` repo as that one houses `llvm`,

**Comment by sdsddsd1** [comment]
@mmatongo : Did you have success to build zig on KISS yet? There is currently work on a wayland wiki article intersecting zig.
https://github.com/kiss-community/wiki/pull/5/files#diff-85d242737d2b3a139617365af85cec5f1c8b1ca201508428d6f99f9fa1bb7b00R206
