### ISSUE TITLE
file runtime error

### ISSUE THREAD

**Issue by ghost** [kisslinux/community#1641]
When `file` is invoked without arguments, or any arguments other than --help, it exits immediately and outputs `Bad system call`. @dylanaraps

**Comment by git-bruh** [comment]
Works fine for me :thinking: 

```
~ $ file
Usage: file [-bcCdEhikLlNnprsSvzZ0] [--apple] [--extension] [--mime-encoding]
            [--mime-type] [-e <testname>] [-F <separator>]  [-f <namefile>]
            [-m <magicfiles>] [-P <parameter=value>] [--exclude-quiet]
            <file> ...
       file -C [-m <magicfiles>]
       file [--help]
~ $ file /usr/bin/file
/usr/bin/file: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, stripped
```

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/58531601/102096286-6fc32b00-3e1c-11eb-85ef-e4c1f6ae482a.png)

**Comment by ghost** [comment]
> Works fine for me thinking
> 
> ```
> ~ $ file
> Usage: file [-bcCdEhikLlNnprsSvzZ0] [--apple] [--extension] [--mime-encoding]
>             [--mime-type] [-e <testname>] [-F <separator>]  [-f <namefile>]
>             [-m <magicfiles>] [-P <parameter=value>] [--exclude-quiet]
>             <file> ...
>        file -C [-m <magicfiles>]
>        file [--help]
> ~ $ file /usr/bin/file
> /usr/bin/file: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, stripped
> ```

Your `file` binary may not be provided by the `file` package.

**Comment by git-bruh** [comment]
Weird, i built the `file` package from the community repo itself, right now.

```
~ # kiss owns /usr/bin/file
file
~ # cat $(kiss s file)/sources
https://astron.com/pub/file/file-5.39.tar.gz
```

**Comment by ghost** [comment]
How curious.

**Comment by ghost** [comment]
On a rebuild, results remain the same.
![image](https://user-images.githubusercontent.com/58531601/102099173-ed3c6a80-3e1f-11eb-9970-9688e2b20ea1.png)
