### ISSUE TITLE
icu: missing make dep

### ISSUE THREAD

**Issue by eudaldgr** [kisslinux/community#1670]
`icu` needs `clang`.
@sdsddsd1

**Comment by sdsddsd1** [comment]
`icu` builds fine with gcc. Your problem is probably `ccache` messing things up. Have a look here https://freenode.logbot.info/kisslinux/20200715#c4400989 .  When disabeling ccache fixes your issue we should find a solution to add this to the package.

**Comment by eudaldgr** [comment]
Oh thanks, that's would be great if there is a solution with `ccache`.

**Comment by sdsddsd1** [comment]
I took the solution from our firefox package to bypass ccache which works for me.
```
export CC="${CC:-/usr/bin/cc}"
export CXX="${CXX:-/usr/bin/c++}"
```
This solution should not break setups where clang/llvm is the default. @dilyn-corner @konimex is this right?

**Comment by dilyn-corner** [comment]
This works. 

Of course the easy fix is to not use `ccache` in the first place.

**Comment by eudaldgr** [comment]
Thanks

**Comment by sdsddsd1** [comment]
@eudaldgr : can this be closed?

**Comment by eudaldgr** [comment]
Okey
