### ISSUE TITLE
Webkit2gtk - dropping packages

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/community#1711]
aloha,
I take a break from the KISS project. Therefore I drop all my packages, especially the ones around webkit2gtk. I think thats all. 
https://github.com/sdsddsd1/kiss-games will probably get outdated, but pull requests will likely get merged (: 
- catclock (praise the cat!)
- fonts:spleen
- glib-network
- [x] gnutls
- gstreamer
- gestreamer-plugins
- gstreamer-plugins-base
- icu
- lesstif
- [x] libgcrypt
- libgpg-error
- libpsl
- libsoup
- libXslt
- netsurf-fb
- nettle
- rdrview (FF reader plugin for the terminal)
- ruby
- [x] sdl2
- [x] sdl
- webkitgtk
- wyeb
- wyebadblock (adblock for webkit)

**Comment by Rio6** [comment]
I'll take sdl and sdl2

**Comment by mmatongo** [comment]
i'll take ruby for my languages repo

**Comment by Vouivre** [comment]
I'll take gnutls.

**Comment by sdsddsd1** [comment]
2 weeks have passed. I have submitted a PR to delete the leftover packages.
