### ISSUE TITLE
gphoto2 in community

### ISSUE THREAD

**Issue by Vouivre** [kisslinux/community#1722]
Hi, 

I have packaged `gphoto2` to access a digital camera. It has the dependency of `libtool`, but I think @dylanaraps  accepted it in community. @git-bruh:  If I create a PR for this package, would you accept it in repo-community ?

**Comment by git-bruh** [comment]
It'll be merged since `libtool` is in community already @Vouivre

**Comment by Vouivre** [comment]
@git-bruh Ok, thank you. 
Have a look at the package for `libgphoto2`. I have never done something like that in a package, I'm not sure it follows exactly the guidelines. Perhpas I missed something. 

I will push two packages: `libgphoto2` and `gphoto2`. 

When I have read this message, I let you close this issue.
