### ISSUE TITLE
emacs out of date

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#183]
See: https://repology.org/projects/?inrepo=kiss_community&outdated=1

@a-schaefers

**Comment by a-schaefers** [comment]
Everybody is still on 26.3 https://repology.org/project/emacs/versions

The 27 versions are snapshots of the development tree and beta

**Comment by dylanaraps** [comment]
Thanks.

Notified Repology. https://github.com/repology/repology-rules/issues/319
