### ISSUE TITLE
epiphany

### ISSUE THREAD

**Issue by protonesso** [kisslinux/community#2]

**Comment by dylanaraps** [comment]
Emacs has been added.

**Comment by a-schaefers** [comment]
i might be wrong, but I believe epiphany uses webkit-gtk and thusly requires dbus. One workaround you guys might consider is installing crud like web browsers using nixpkgs. Install nixpkgs, then nix-env -i chromium (or whatever) and be done with it

**Comment by a-schaefers** [comment]
hey this should be doable now that we have webkit2gtk

**Comment by dylanaraps** [comment]
It might be tricky:

> Epiphany's main goal is to be integrated with GNOME, as well as similar desktops (notably elementary OS). We don't aim to make Epiphany usable outside these environments.

https://github.com/GNOME/epiphany#gnome-integration

**Comment by dylanaraps** [comment]
Closing this as I'd rather not deal with GNOME incompatibilities due to above or the inclusion of a bunch of crap with which more crap will come to depend on.
