### ISSUE TITLE
oil-shell out of date

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#251]
@jedahan 

See: https://repology.org/projects/?inrepo=kiss_community&outdated=1

**Comment by jedahan** [comment]
Is there a way for repology to email when something goes out of date?

**Comment by dylanaraps** [comment]
I'll see if repology can add maintainer support for the KISS repositories which means you'd get a page similar to this: https://repology.org/maintainer/0x9fff00%40aur

**Comment by dylanaraps** [comment]
https://github.com/repology/repology-updater/issues/992

**Comment by dylanaraps** [comment]
Repology has added support displaying and tracking KISS package maintainers. When the website next updates you will have a page dedicated to the packages you maintain, displaying versions, etc.

There are also feeds you can subscribe to which allow you to be notified of outdated packages.

**Comment by jedahan** [comment]
awesome, thank you! would be nice to be in the top 10 especially once we hit >1000 packages :)
