### ISSUE TITLE
Add a maintainer file for each package

### ISSUE THREAD

**Issue by konimex** [kisslinux/community#29]
This isn't that urgent (i.e. enhancement rather than bug) and only useful for meta purposes and should not interfere with the package manager. But I think we can add a `maintainer` file for clarity (who gets to maintain this package? and who should *we*, as in users, contact in case shit hits the fan?)

I know we can check who committed first to the package (i.e. a simple `git log` without options), but as you can see, `git`'s own `git log` is not very reliable for this. You have to dig into `git blame` each file, but that won't work if the file/commit is overwritten.

For example, `bspwm` which I originally submitted has the first `git log` commit attributed to you (just check `git log $DIR_TO_COMMUNITY/bspwm` or [GitHub's own history](https://github.com/kisslinux/community/commits/master/community/bspwm)), so if we take this at face value, you're the one maintaining this package, not me. This also can work as an additional "commitment" by the maintainer of the respective packages should one wants to submit one's own package.

**Comment by dylanaraps** [comment]
> For example, bspwm which I originally submitted has the first git log commit attributed to you

This is only due to the repository split no?

**Comment by dylanaraps** [comment]
For example (`berry` added after the split):

```
commit ef36a72e61b5ddd1adce605c54736cdf7df333e6
Author: Cliford Sab <clifordsab@gmail.com>
Date:   Sat Sep 21 11:46:39 2019 +0800

    berry: bump to 0.1.3

commit 2644e848b024846eb39ed15678571f52fdc88b8d
Author: Cliford Sab <clifordsab@gmail.com>
Date:   Sun Sep 15 23:06:40 2019 +0800

    berry: new package at 0.1.2
```

**Comment by konimex** [comment]
Oh right. I think so. So it won't really affect new packages.

So, what would happen to the old packages, then? If you're fine with leaving it as is then I'm good.

**Comment by dylanaraps** [comment]
Old packages will be listed under my name until each maintainer pushes
a new commit if and when their packages require a change or have an
update.
