### ISSUE TITLE
Split packages for poppler

### ISSUE THREAD

**Issue by Vouivre** [kisslinux/community#307]
Hello,

I'm the maintainer of `poppler-glib`. I need it for the pdf viewer `zathura`. I also need some utilities for manipulating pdf files from `poppler`, like `pdfseparate` to extract some pages of a pdf document. 

I had a look in other distribution to see how it's packaged. Basically, I see two possibilities:
1. `poppler-glib`, `poppler`, `poppler-utils`, like in Alpine
2. `poppler-glib`, `poppler`, like in Crux. 

For the first one, `poppler-glib` contains only libraries related to glib and `poppler` only the libraries related to poppler. `poppler-utils` contains no header files, only tools to manipulate pdf files. 

For the second, `poppler-glib` contains only the libraries related to glib, `poppler` contains the tool and library related to poppler, including header files. 

The second possibility seems good to me, and there is one package less to maintain. What do you think before I package it ?

**Comment by dylanaraps** [comment]
I think a single package called `poppler` is best (if this is possible).

**Comment by Vouivre** [comment]
Ok, I'll try locally.

**Comment by Vouivre** [comment]
Tested and it works! 

So we can remove `poppler-glib` and I have to remove the dependency in `zathura-pdf-poppler` and replace `poppler-glib` with `poppler`. 

What's the best to do the transition for the users ? 

I can imagine the following: 

- delete the package `poppler-glib`
- adapt the dependencies of `zathura-pdf-poppler`
- add the package `poppler`

Do you have another proposal or is it ok for you ? 

If it's ok, how can we notify the user that `poppler-glib` is no longer needed ? I know it's possible to add some text after installing a package. I could use that feature and a message will be displayed that `poppler-glib` can be removed. 

Is it still alright for you ?

**Comment by dylanaraps** [comment]
Sounds good to me. :)

**Comment by Vouivre** [comment]
Pull Request created. When it's merged, I let you close this issue.
