### ISSUE TITLE
Runit: packaging new init-supervisor system

### ISSUE THREAD

**Issue by cemkeylan** [kisslinux/community#332]
It is me, yet again. Dropping the busybox dependency one package at a time.

Jokes aside, I am packaging runit and runit-init. I will be pushing the WIP package in a moment and require reviews and testing.

**Comment by konimex** [comment]
Since I'm also planning to do this, what are you planning for `/etc/runit/1` and `3`? Personally I would symlink them to `baseinit`.

**Comment by cemkeylan** [comment]
@konimex Yup, I did that and tested it. Works good.

**Comment by a-schaefers** [comment]
Just leave gnu shepherd for me to package, KTHX :rofl:

**Comment by cemkeylan** [comment]
@a-schaefers I can leave systemd for you to package :stuck_out_tongue:
