### ISSUE TITLE
runit: manage gettys as services

### ISSUE THREAD

**Issue by a-schaefers** [kisslinux/community#351]
Hi,

First and foremost, **great work @cemkeylan** for packaging runit. This issue would not be possible without all of your hard work.

I have some ideas for further development. Please let me know what you think?

1. I would like to see service files included with runit for "agetty" and "getty" (busybox)

2. Remove the while loop from /etc/runit/2

3. Add a post-install message telling the user to enable the getty service(s) of his choice. 

My reasoning is the while loop in /etc/rc.d/ makes sense for something like sinit, but not so much for runit. I think runit should manage gettys as services, as mainstream runit distros do likewise and the setup is more unified as such.

**Comment by cemkeylan** [comment]
I mean, it is pretty much the same for sinit and busybox-init, we are still running runit as the system supervisor. What is the reasoning for adding getty as a system service just for runit-init?

**Comment by cemkeylan** [comment]
It is much simpler in my opinion to have a for-loop, or an inittab entry than to manage runit services for each getty we are using. The user has to have 6 different services just for running 6 gettys

**Comment by a-schaefers** [comment]
I see where you are coming from as well. 3 lines to be replaced by a handful of directories each with 2 or three files and a symlink does not appear very simple.

However, as runit combines init with service supervision it still seems ibkt natural to me to include getty as a service of runit, the way void does. It may be thought of as simpler, in this way, too depending on how one looks at it.

Also, inittab does not work with runit, right? Isn't that a busybox / sysv thing?

Curious if others would chime in here to see if I'm all alone on this?

**Comment by dylanaraps** [comment]
I like the `rc.d` approach better too. It leaves room for me to write a portable "interface" to the gettys so one doesn't have to worry about commenting/uncommenting lines etc.

**Comment by cemkeylan** [comment]
Yeah, I would even suggest launching getty on `rc.d/getty.boot` with baseinit by default and remove the getty from `2` and `inittab`. This way we don't have to worry about getty on any of the inits.

On 13 February 2020 16:12:47 GMT+03:00, dylan <notifications@github.com> wrote:
>I like the `rc.d` approach better too. It leaves room for me to write a
>portable "interface" to the gettys so one doesn't have to worry about
>commenting/uncommenting lines etc.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kisslinux/community/issues/351#issuecomment-585747632

-- 
Cem Keylan

**Comment by a-schaefers** [comment]
The more I think about it, I now believe @cemkeylan has it right. Since we are not using busybox runit to manage getty, why would we use runit runit to manage getty? Unless we want to change both to be managed as services, things should remain as they are.

I also like @cemkeylan's idea re: being done with inittab and using rc.d/getty.boot with baseinit by default.

**Comment by a-schaefers** [comment]
Closing this, feel free to comment, though, if anyone else thinks this should be revisited.
