### ISSUE TITLE
Packages I will no longer maintain. Looking for maintainers.

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#374]
These will be dropped from the repository in a week's time. These are packages I picked up after the maintainer disappeared or packages which I would no longer like to maintain.

Regardless, I have too much on my plate in Community. Ideally I'd participate in Community like any other user when maintaining packages. Don't rely on me to pick up any orphans. 

Please comment below if you'd like to take over maintainer-ship for any of the following:

- [x] ~~`bdf2pcf`~~ @aaronNGi 
- [x] ~~`bspwm`~~ @konimex 
- [x] ~~`conky`~~ @dzove855 
- [x] ~~`cryptsetup`~~ @konimex 
- [x] ~~`dmenu`~~ @konimex 
- [ ] `extra-cmake-modules`
- [ ] `falkon`
- [x] ~~`fd`~~ @kiedtl 
- [x] ~~`feh`~~ @konimex 
- [x] ~~`terminus-font`~~ @aaronNGi 
- [x] ~~`glib-networking`~~ @cemkeylan
- [x] ~~`gnutls`~~ @konimex 
- [x] ~~`go`~~ @konimex 
- [x] ~~`i3`/`i3-gaps`~~ @sirtomato999 
- [x] ~~`imlib2`~~ @konimex 
- [x] ~~`lemonbar`~~ @konimex 
- [x] ~~`libaio`~~ @konimex 
- [x] ~~`libarchive`~~ @konimex 
- [x] ~~`libev`~~ @konimex 
- [x] ~~`libexif`~~ @konimex 
- [x] ~~`libgcrypt`~~ @a-schaefers 
- [x] ~~`libgpg-error`~~ @a-schaefers 
- [x] ~~`libpsl`~~ @cemkeylan
- [x] ~~`libsoup`~~ @cemkeylan
- [x] ~~`libxslt`~~ @cemkeylan
- [x] ~~`lua`~~ @dzove855
- [x] ~~`lvm2`~~ @konimex 
- [x] ~~`lynx`~~ @dzove855 
- [x] ~~`lzo`~~ @a-schaefers 
- [x] ~~`mc`~~ @electimon
- [x] ~~`nano`~~ @periish
- [x] ~~`neovim`~~ @ioraff 
- [x] ~~`nettle`~~ @a-schaefers 
- [x] ~~`nmap`~~ @zachhweed 
- [x] ~~`nss`~~ @periish
- [x] ~~`os-prober`~~ @konimex 
- [x] ~~`pciutils`~~ @a-schaefers 
- [x] ~~`pcre`~~ @ioraff  
- [x] ~~`popt`~~ @ioraff 
- [ ] `qt5`
- [ ] `qt5-webengine` (I will help with patches, etc for this one if needed).
- [ ] `qt5-declarative`
- [ ] `qt5-svg`
- [ ] `qt5-webchannel`
- [ ] `qt5-webengine`
- [ ] `qt5-x11extras`
- [x] ~~`ripgrep`~~ @kiedtl 
- [x] ~~`ruby`~~ @cemkeylan 
- [x] ~~`rxvt-unicode`~~ @konimex 
- [x] ~~`sbase`~~ @cemkeylan
- [x] ~~`setroot`~~ @sirtomato999
- [x] ~~`sxhkd`~~ @konimex 
- [x] ~~`sxiv`~~ @cemkeylan
- [x] ~~`tmux`~~ @konimex 
- [x] ~~`tree`~~ @aaronNGi 
- [x] ~~`ubase`~~ @cemkeylan
- [x] ~~`weechat`~~ @konimex 
- [x] ~~`xsel`~~ @aaronNGi

**Comment by konimex** [comment]
I'll take the following: 
- `bspwm`
- `cryptsetup`
- `dmenu`
- `go`
- `gnutls`
- `imlib2`
- `lemonbar`
- `libarchive`
- `lvm2`
- `os-prober`
- `rxvt-unicode`
- `sxhkd`
- `tmux`
- `weechat`

As for `nettle`, isn't that packaged for a dependency?

**Comment by a-schaefers** [comment]
I will take
```
gnutls
pciutils
lzo
libgpg-error
nettle
```

**Comment by a-schaefers** [comment]
And `libgcrypt`

**Comment by dzove855** [comment]
I go for:

`conky
lynx
` 
Will have a look tonight about the rest what is not taken.

**Comment by cemkeylan** [comment]
Ugh... Can I order some bloatkit2gtk dependencies please?

`libsoup libxslt libpsl glib-networking`

Also to the side, I will be ordering some `sbase ubase sxiv`

**Comment by aaronNGi** [comment]
I'll take `terminus-font` and `bdftopcf`.

**Comment by dylanaraps** [comment]
@cemkeylan You'll need `ruby` for `webkit2gtk` as well.

**Comment by dylanaraps** [comment]
NOTE: The simplest way to "trick" `git` into updating maintainer status is to append a space to the end of the version file. Not ideal, but the simplest way of doing this.

**Comment by zachhweed** [comment]
I'll take `nmap`

**Comment by ioraff** [comment]
I'll take `neovim`

**Comment by periish** [comment]
I'll take nano and NSS.

**Comment by dilyn-corner** [comment]
I could take Falkon + deps if nobody else is willing.

**Comment by cemkeylan** [comment]
@dylanaraps I didn't see your note about ruby, sure I'll gladly take that as well.

**Comment by ioraff** [comment]
@konimex `popt` is only required for cryptsetup. I'll take it if you won't.

**Comment by konimex** [comment]
I totally forgot about cryptsetup's deps (thought it was just lvm2). If you want to, sure.

**Comment by ioraff** [comment]
will do.

**Comment by sirtomato999** [comment]
ill take i3 and setroot

**Comment by kiedtl** [comment]
I will take `fd` and `ripgrep`.

**Comment by electimon** [comment]
I can take MC

**Comment by dylanaraps** [comment]
@sirtomato999 Heads up, i3 had an update.

**Comment by dylanaraps** [comment]
Heads up, someone must take `pcre` as a lot depends on it.

**Comment by dylanaraps** [comment]
@dilyn-corner No one else wants Falkon, qt5 and friends. They're yours if you like.

**Comment by dylanaraps** [comment]
@dilyn-corner One last bump before I remove them from the repositories. (The 7 days is up). :+1:

**Comment by dilyn-corner** [comment]
I'll whisk them away to the safety of my care 

Feb 21, 2020, 8:17 AM by notifications@github.com:

**Comment by dylanaraps** [comment]
Sold.
