### ISSUE TITLE
tor is out of date.

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#379]
- 15 days out of date so far.
- Will be orphaned if no response.

@IslandAlpha

**Comment by dylanaraps** [comment]
Would anyone like to maintain this package?

**Comment by IslandAlpha** [comment]
Sorry for the delay, I switched off of KISS as my daily driver since it doesn't meet all my needs as of now.

Do you mind if I stay as the maintainer for this package?

**Comment by IslandAlpha** [comment]
Tor will be updated by the end of the day

**Comment by dylanaraps** [comment]
Sure thing. You should be able to update the package via a chroot of KISS. Just unpack the install archive (as root) and chroot into it. :+1:
