### ISSUE TITLE
More packages up for adoption: (I will no longer be maintaining these...)

### ISSUE THREAD

**Issue by a-schaefers** [kisslinux/community#415]
compton
~~libxdg-basedir (required by compton & picom)~~ `konimex`
~~libconfig (required by compton & picom)~~ `konimex`

~~netsurf~~ `IslandAlpha`
~~perl-html-parser (req. by netsurf)~~ `IslandAlpha`
~~perl-html-tagset (req. by netsurf)~~ `IslandAlpha`

esetroot

keychain

**Comment by konimex** [comment]
I'll take both `libxdg-basedir` and `libconfig`.

**Comment by IslandAlpha** [comment]
I'll take netsurf and its deps
