### ISSUE TITLE
man-pages-5.05: fails to build as normal user

### ISSUE THREAD

**Issue by aaronNGi** [kisslinux/community#440]
@artemkobets 

This fails to build as normal user because the default target `all` includes `remove`, which touches the rootfs (`rm -f`). We want to avoid building packages as root in kiss. Instead of just `make
` the build file could be changed to use `make install` instead.

Log:

    for i in man?/*; do \
    	rm -f /usr/share/man/"$i" /usr/share/man/"$i".*; \
    done
    for i in man?; do \
    	install -d -m 755 /home/ang/.cache/kiss/pkg-25777/man-pages/usr/share/man/"$i" || exit $?; \
    	install -m 644 "$i"/* /home/ang/.cache/kiss/pkg-25777/man-pages/usr/share/man/"$i" || exit $?; \
    done
    rm: can't remove '/usr/share/man/man5/tzfile.5': Permission denied
    rm: can't remove '/usr/share/man/man7/man.7': Permission denied
    rm: can't remove '/usr/share/man/man8/tzselect.8': Permission denied
    rm: can't remove '/usr/share/man/man8/zdump.8': Permission denied
    rm: can't remove '/usr/share/man/man8/zic.8': Permission denied
    make: *** [Makefile:8: remove] Error 1

**Comment by dylanaraps** [comment]
@artemkobets (Did you not test the build before submitting a PR?)

**Comment by dylanaraps** [comment]
Closing this, see my above comment. Packages have been dropped and can be submitted again.

**Comment by artemkobets** [comment]
Thanks @aaronNGi!
Sorry for this one, should have paid more attention to the build output.
I'll resubmit the packages shortly.
