### ISSUE TITLE
mercurial build fails

### ISSUE THREAD

**Issue by jedavies-dev** [kisslinux/community#488]
I get the following error when attempting to build mercurial:

-> mercurial Building package (1/1)
-> mercurial Extracting sources
-> mercurial Starting build
Collecting docutils
  Downloading https://files.pythonhosted.org/packages/81/44/8a15e45ffa96e6cf82956dd8d7af9e666357e16b0d93b253903475ee947f/docutils-0.16-py2.py3-none-any.whl (548kB)
Installing collected packages: docutils
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/docutils'
Consider using the `--user` option or check the permissions.

WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
-> mercurial Build failed

All my installed packages are up to date.

**Comment by dylanaraps** [comment]
I've removed the package. 

@sirtomato999 Did you not test this before submission? 

This goes for everyone. I can't keep doing this. Test your packages before submission. I shouldn't have to repeat myself.
