### ISSUE TITLE
libcap wrong pkgconfig install directory

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#499]
```
rircEFFD2 adamantium[m]: the package libcap seems to be wrong. stuff that should be in /usr/lib/pkgconfig is in /usr/pkgconfig
```

@a-schaefers

**Comment by sdsddsd1** [comment]
@a-schaefers : Libcap is still broken for me.  The files `libpsx.pc` `libcap.pc` are still in /usr/lib.
Config arg `PKGCONFIGDIR=/usr/lib/pkgconfig` puts it in its right place

**Comment by dylanaraps** [comment]
Fucking hell. Test your shit please everyone.

**Comment by a-schaefers** [comment]
Sorry guys I really dropped the ball on this. Should be all good now.
