### ISSUE TITLE
zathura pdf reader

### ISSUE THREAD

**Issue by tristelune1** [kisslinux/community#50]
Hello,

I'm trying to package zathura the PDF reader, but I don't manage. I would like to know if there is a fix to my problem. But we don't need to spend a lot of time, because I packaged zathura for another linux distribution and a lot of python modules were needed. If it's still the case, I will use mupdf which I have already packaged. Zathura is built with meson. I get at the end of the log:

```
Compiler stderr:

Library magic found: YES
Pkg-config binary for MachineChoice.HOST is cached.
Determining dependency 'libseccomp' with pkg-config executable '/usr/bin/pkg-config'
PKG_CONFIG_PATH:
Called `/usr/bin/pkg-config --modversion libseccomp` -> 0
2.4.1
PKG_CONFIG_PATH:
Called `/usr/bin/pkg-config --cflags libseccomp` -> 0

PKG_CONFIG_PATH:
Called `/usr/bin/pkg-config libseccomp --libs` -> 0
-L/usr/lib -lseccomp
PKG_CONFIG_PATH:
Called `/usr/bin/pkg-config libseccomp --libs` -> 0
-lseccomp
PKG_CONFIG_PATH:
Called `/usr/bin/pkg-config libseccomp --libs --static` -> 0
-lseccomp
Run-time dependency libseccomp found: YES 2.4.1
Configuring zathura-version.h using configuration
Pkg-config binary for MachineChoice.BUILD is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default pkg-config fallback at pkg-config
Trying pkg-config binary pkg-config for machine MachineChoice.BUILD at ['/usr/bin/pkg-config']
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Determining dependency 'glib-2.0' with pkg-config executable '/usr/bin/pkg-config'
PKG_CONFIG_PATH:
Called `/usr/bin/pkg-config --modversion glib-2.0` -> 0
2.62.1
PKG_CONFIG_PATH:
Called `/usr/bin/pkg-config --cflags glib-2.0` -> 0
-I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
PKG_CONFIG_PATH:
Called `/usr/bin/pkg-config glib-2.0 --libs` -> 0
-L/usr/lib -lglib-2.0
PKG_CONFIG_PATH:
Called `/usr/bin/pkg-config glib-2.0 --libs` -> 0
-lglib-2.0
PKG_CONFIG_PATH:
Called `/usr/bin/pkg-config glib-2.0 --libs --static` -> 0
-lglib-2.0 -pthread
Program rsvg-convert found: NO
WARNING: Gettext not found, all translation targets will be ignored.

data/meson.build:22:0: ERROR: Tried to assign an invalid value to variable.
```

For me it's not clear what the error is. I assume it's the PKG_CONFIG_PATH which is empty. Does somebody has an idea how to fix it ? If you want to try to build it, the problem you will need a lot of dependencies. I tried to package `librsvg` but I give up. There is a `gtk-doc` dependency and it will take too much packages.

**Comment by dylanaraps** [comment]
> WARNING: Gettext not found, all translation targets will be ignored.

NLS/Gettext need to be set to `auto` or just set to `no`. 

Edit: 

It seems as though Zathura offers no option to disable `gettext` so try this command at the top of the `build` file.

```sh
sed -i'' "/subdir('po')/d" meson.build
```

**Comment by tristelune1** [comment]
You point me in the right direction. I have probably to patch another build file for meson. But now I have another problem. I have to install `libnotify`. But to install it, I need `gobject-introspection`. I have packaged `gobject-introspection`, but after that the build of `libnotify` fails, because it needs some `gir` files for from `gdk-pixbuf`. It means, it would be necessary to build those files with `gdk-pixbuf`. I have no idea what is the best. My questions:

- why did you remove `*.gir` files from `gdk-pixbuf` and what are those files (I mean the use of them)?
- Probably I can remove the dependency of `gobject-introspection` and there would be no problem with `*.gir` files. Do you know what brings `gobject-introspection` ?

**Comment by dylanaraps** [comment]
You're better off omitting both `libnotify` and `gobject-introspection` from Zathura (*which should be possible*).

**Comment by tristelune1** [comment]
I use at the moment `mupdf`. I write some pdf documents with `latex` and the problem is `mupdf` doesn't refresh the document when a change is done. I know `zathura` refresh the document. I don't know `libnotify`, I thought `zathura` uses `libnotify` to refresh a document when there are some changes. Am I wrong ? Or can we get the same results by using something else ?

**Comment by tristelune1** [comment]
Thank you for all your help. The pull request has been created!
