### ISSUE TITLE
libpod

### ISSUE THREAD

**Issue by axpira** [kisslinux/community#51]
Please,

Add https://github.com/containers/libpod to repo is a replacement without a deamon of docker

Thanks

**Comment by dylanaraps** [comment]
Distributions seem to package it as `podman`.

Dependencies from void:

```
hostmakedepends="pkg-config go-md2man"
makedepends="gpgme-devel libseccomp-devel device-mapper-devel"
depends="runc conmon cni-plugins slirp4netns containers.image"
```
> https://github.com/void-linux/void-packages/blob/master/srcpkgs/podman/template

**Comment by axpira** [comment]
Sorry the title is wrong it's podman.io and not postman.io

**Comment by periish** [comment]
Might package this, have got gpgme and libseccomp packaged and building.

**Comment by dylanaraps** [comment]
It's a bit much for community. I wouldn't like anything to do with `btrfs-progs` either.

**Comment by dylanaraps** [comment]
I don't want to see this in Community.
