### ISSUE TITLE
Bluez

### ISSUE THREAD

**Issue by axpira** [kisslinux/community#56]
Please add a bluetoothctl command line to enable possibility to connect bluetooth devices

**Comment by axpira** [comment]
It`s on bluez package.

I tried to compile but I'm getting this error:

```
configure: error: D-Bus >= 1.6 is required
``` 

I tried with this:
```
./configure --prefix=/usr --with-udevdir=/usr/lib/udev --disable-systemd --disable-debug --disable-test --disable-nfc --disable-sap --disable-cups --disable-mesh --disable-android
```

**Comment by konimex** [comment]
Unless `--disable-dbus` can work here I don't think Dylan can add it.

**Comment by dylanaraps** [comment]
Yeah, `dbus` is mandatory with Bluez sadly. I looked into this a while ago.

**Comment by axpira** [comment]
Do you known any other option to use bluetooth?

**Comment by dylanaraps** [comment]
Sadly, no. Bluetooth on Linux **require** `dbus`. Even embedded devices are forced to run it to achieve working Bluetooth. I'd love it if somebody could prove me wrong here!

**Comment by Jackojc** [comment]
Should this issue be closed or are you investigating alternatives?

**Comment by dylanaraps** [comment]
This could be an option for those wanting Bluez without the use of `dbus`: https://github.com/clbr/nobus

> Should this issue be closed or are you investigating alternatives?

Regardless, this acts as an answer to the question of "Is Bluez packaged"?

**Comment by dylanaraps** [comment]
Closing this as it won't ever be packaged. Users needing bluetooth can package both `dbus` and `bluez` themselves.
