### ISSUE TITLE
qrencode: remove or adopt

### ISSUE THREAD

**Issue by IslandAlpha** [kisslinux/community#564]
I can't even remember what this was packaged for, and no packages that I know of use it.

Unless anybody else uses this and wants to adopt it this will be gone in one week.

**Comment by Vouivre** [comment]
Hi, I use it, so I will adopt this package. I have one question: it is possible to change manually the maintainer on repology ? I don't have a look regularly on repology, so the probability is high I will miss new releases, including for other software.

**Comment by dylanaraps** [comment]
Send a PR adding a trailing space to the version file (`"1.0.0 1"` becomes `"1.0.0 1 "`).

**Comment by Vouivre** [comment]
Thank you! I will use this trick for my other packages. PR done.
