### ISSUE TITLE
Package documentation

### ISSUE THREAD

**Issue by tristelune1** [kisslinux/community#57]
Hi,

what are we supposed to do with the documentation of a package which is found in `usr/share/info`, `usr/share/gtk-doc`, etc. As a maintainer are we supposed to delete it or is it the choice of the user to delete it with the variable `KISS_RM` ?

Until now, I disabled the documentation in the package, but probably sometimes it is build automatically and the only way to get ride of this documentation is to delete it with `rm`. The questions is for thoses cases.

**Comment by dylanaraps** [comment]
If the documentation requires no additional software to build, it's better to leave it default and let the user decide with `KISS_RM`. If the software requires additional dependencies to build the documentation, it's better to disable it altogether.

**Comment by tristelune1** [comment]
Thank you :+1: !  Perhaps you should add it to the guidelines, unless I didn't see where it's written. I let you choose and close this question. Thank you! :smile:
