### ISSUE TITLE
gnutls: orphan

### ISSUE THREAD

**Issue by konimex** [kisslinux/community#599]
I won't be maintaining GnuTLS anymore. However since both Emacs and GnuPG depends on the package, I'll need to ask maintainer(s) of both packages to take over (if possible).

**Comment by konimex** [comment]
@a-schaefers since both Emacs and GnuPG2 depend on GnuTLS, would you mind if you take over this package? Thanks.

**Comment by a-schaefers** [comment]
Not a problem :)
