### ISSUE TITLE
First try to package cups

### ISSUE THREAD

**Issue by Vouivre** [kisslinux/community#63]
Hello,

I need to use a printer and I created a package for cups. Basically I took [the package from crux here] (https://crux.nu/ports/crux-3.5/opt/cups/Pkgfile). 

Unfortunately my printer is not found. Even if I try to install it manually, it doesn't work. I get an error  in cups: `File not found`. I have also created a package for the drivers. My printer is found with `snmp`: [log file](http://pastebin.fr/58993)

So my printer is found with snmp. But not with the GUI. I thought I could try with `avahi` but there are a lot of dependencies and `dbus` is one of them. On crux it worked, but I don't know what is missing. I have only packaged cups, there are no dependency for the moment. Perhaps `linux-pam` is missing, but it's not packaged for KISS and I don't know if there is a workaround. Does somebody managed to install a printer ?

**Comment by dylanaraps** [comment]
So it builds and install correctly but then fails to work?

**Comment by dylanaraps** [comment]
It might be worth looking at how Void, Alpine or Sabotage package `cups` and friends.

**Comment by tristelune1** [comment]
Yes, it builds and I can access cups with the browser. It also finds the installed driver. But it fails to print something. I'll try to contact the package maintainer of those distribution.

**Comment by tristelune1** [comment]
Update: I was able to package `cups`. But I have a lot of details to check. Basically:

- `cups-filters` was missing
- I can't add a printer with the web interface. I have to use the command `lpadmin`

I packaged the drivers for my printer, unfortunately, they are bad, as I expected. With all distributions it was the same. So I try to install the driver "Turboprint" for my epson printer, but it's a binary and it's built with `glibc`. I did a bug report and a preversion were released, so a fix should come. When the fix will be ready, I will finish to test and to package cups.

**Comment by Vouivre** [comment]
It's time to finish the packaging. In between I discovered other projects:

- [lprng](http://www.lprng.com/), but I'm a little bit skeptical. The last update is was in 2015. If I remember right, the team of Debian made some changes, but I'm afraid it's not reliable. Or there will be some problems in the future. 
- it seems possible to print with `netcat`, but I don't know how and not sure it's as easy as `cups`.

So `cups` still seems a good alternative. With other distributions, it was possible to use a web interface to install the printer. With my package, it's not possible. A dependency is probably missing or more. But there is a tool in `cups`, `lpadmin` and it's possible to install the printer with the commandline. If we add something in the wiki, probably the commandline is enough. So I would compile `cups` without the web interface. Would it be alright for you ?

**Comment by dylanaraps** [comment]
lprng saw changes mid 2019 according to this link: https://sourceforge.net/p/lprng/lprng/ci/master/tree/ might not be as dead as we think!

Command-line only is fine. :+1:

**Comment by Vouivre** [comment]
Ok, I'll have a look at it. I have created a package, now I will have a look at how to install `lprng` and use it. It seems more lightweight than `cups`. But I have no idea about which configuration files to use or if somes services are needed. I'll dig it this week.

**Comment by dylanaraps** [comment]
Any updates on this? How's it going?

**Comment by Vouivre** [comment]
Sorry, I had no time to test. I will try to package `lprng` tomorrow. But I'm not sure it's worth trying it. My goal was to have a lightweight version of `cups`. I have already tried to get rid of 'unnecessary' files from `cups` and it's possible to reduce the size of cups a lot. More tomorrow.

**Comment by RibalGZ** [comment]
The simples printing system I know about is [prout](https://git.2f30.org/prout/file/README.html).
It depends on cups.h, but doesn't need any cups server running.

**Comment by Vouivre** [comment]
After packaging `lprng` it's more lightweight than `cups`, but I prefer packaging `cups`. The quality of printing with my printer is not very good and to improve it I need a software which probably need `cups`. So I will package it. By the way, thank you for your suggestion RibalGZ! I could also try `prout`. So the next step for me is the PR.

**Comment by Vouivre** [comment]
I tried to create the package in a chroot, I'm not at the end and honestly there is a lot to do. To compile `cups`, I have no dependencies, it's alright. To `cups-filters`, it's another story. For the moment, my dependency list is:

```
fontconfig
freetype-harfbuzz
ghostscript
glib
lcms2
libjpeg-turbo
libpng
poppler
qpdf
tiff
```

For the moment `qpdf` and  `ghostscript` are not packaged. `poppler` need a modification in the build file. I'm still not at the end, I need to package mupdf-tools. I don't know what you think, it's probably time to have a look at `prout`. What do you think ?

By the way, I have always used `cups`, because it was standard. What is the advantage of a cups server ? Is it, that it's listening to coming jobs ?

**Comment by Vouivre** [comment]
@RibalGZ : did you already tried `prout` ? No problem to compile `prout`, but I get the error: 
```
No default printer configured
```

 Any idea what can I do ? Otherwise I can direct contact the author of `prout`.

**Comment by RibalGZ** [comment]
> @RibalGZ : did you already tried `prout` ? No problem to compile `prout`, but I get the error:
> 
> ```
> No default printer configured
> ```
> 
> Any idea what can I do ? Otherwise I can direct contact the author of `prout`.

I don't have a printer to test, but according to the README:

> Just set your default printer in client.conf(5) and start printing.

Where client.conf(5) corresponds to: https://www.cups.org/doc/man-client.conf.html

I hope it helps.

**Comment by Vouivre** [comment]
Update: I still want to package `cups` or `prout`, but at the moment I have no time to invest on it. In those crazy moments, I can only invest some time on tasks I really need or don't require a lot of time. In between if somebody needs my `build` file for cups, just ask.

**Comment by eudaldgr** [comment]
> Update: I still want to package `cups` or `prout`, but at the moment I have no time to invest on it. In those crazy moments, I can only invest some time on tasks I really need or don't require a lot of time. In between if somebody needs my `build` file for cups, just ask.

I want your build's of `cups` and `lprng`

**Comment by eudaldgr** [comment]
> Update: I still want to package `cups` or `prout`, but at the moment I have no time to invest on it. In those crazy moments, I can only invest some time on tasks I really need or don't require a lot of time. In between if somebody needs my `build` file for cups, just ask.

@Vouivre I want your build's of `cups` and `lprng`

**Comment by Vouivre** [comment]
@eudaldgr 

I will create a repository until tomorrow with the necessary build files. But in between the `build` for cups:

````
#!/bin/sh -e

CC=cc CXX=c++ \

./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --with-logdir=/var/log/cups \
    --with-cups-user=lp \
    --with-cups-group=lp \
    --with-languages=en \
    --without-pam \
    --without-rcdir \
    --with-optim="$CFLAGS" \
    --disable-webif \
    --disable-gssapi \
    --disable-systemd \
    --disable-gnutls \

make
make BUILDROOT="$1" install

rm -rf "$1/usr/share/cups/templates"
rm -rf "$1/usr/share/icons"


# start script and pam module
#install -D -m 755 cups.rc "$1"/etc/rc.d/cups
#install -D -m 644 cups.pam "$1"/etc/pam.d/cups
````

You also need `cups-filters`. More tomorrow.

**Comment by Vouivre** [comment]
I have added some packages necessary for `cups` on my `kiss-repository`. If you still miss something, you can take it from that repository. Take into account some dependencies are missing. You will have to add them manually. 

Side note: the web interface doesn't work. Use `lpadmin` to add your printer.

**Comment by Vouivre** [comment]
I just had a look at `prout`. For me I won't go that way: a cups server is necessary, so `cups` is needed. I will go back and test `lprng` or trying to have a minimal installation of cups.

**Comment by Vouivre** [comment]
I had finally time to investigate the build of cups. I will have soon a build to test. I will package `cups`. First, it's needed for my printer. Secondly, it seems it has more features than `lprng`. I think it's good to have a package for the user which use a printer. 

I will test my package, perhaps I have manage to get rid of the dependency of `mupdf`. I'm not sure `ghostscript` is needed. I will print this week and check it.

**Comment by Vouivre** [comment]
After a first try, I can print without `mupdf`. So I can get ride of the `mupdf` dependency. 

To package `cups`, I need to create four packages:

- `cups`
- `cups-filters`
- `ghostscript` : necessary for `cups-filters`
- `qpdf`: necessary for `cups-filters`

And I probably need to do a modification to `poppler`.

Is it ok to proceed in that way ?

**Comment by dylanaraps** [comment]
Nice! Sounds good to me. Great work.

**Comment by Vouivre** [comment]
Ok, so it needs now some more tests. The packages will arrive the next days.
