### ISSUE TITLE
Restructure repo

### ISSUE THREAD

**Issue by onodera-punpun** [kisslinux/community#643]
This issue is also applicable to `repo`. Currently my repo directory looks like this:

```
repos/repo/core -> <ports>
repos/repo/extra -> <ports>
repos/repo/xorg -> <ports>
repos/community/community -> <ports>
repos/punpun -> <ports>
```

Kind of inconsistent and messy.
It would be way nicer looking like this imo:

```
repos/core -> <ports>
repos/extra -> <ports>
repos/xorg -> <ports>
repos/community -> <ports>
repos/punpun -> <ports>
```

For this core, extra, testing and xorg would have to be split into three separate repositories, and every repository would have to need its ports in the root directory. Thoughts?

**Comment by cemkeylan** [comment]
You could technically do something like this yourself. Move `repo` and `community` to some other directory. Then, you can symbolically link them to a single directory.

Imagine the actual structure looks like this

```
.hidden/repo
.hidden/community
repos/punpun
```

You can then do

``` sh
# In the repos directory
for repository in repo/core repo/extra repo/xorg community/community ; do
    ln -sfv ../.hidden/$repository .
done
```

This will end up in the directory structure you would like.

**Comment by dylanaraps** [comment]
Community is structured exactly like the other (git) repository to allow for the possibility of new community based repositories in the future. The most likely (and obvious) being a community-testing repository.

Going the other way and splitting the official repositories in three is not something I'd like to do. It'd be a large breaking change and require manual intervention by every user. I'd very much rather we keep the structure and repositories as they are. 

I can't totally rule out a change like this sometime in the future but I don't think we're at a point where we need to make this change now. We'll see how the existing structure continues and re-explore this if need be.
