### ISSUE TITLE
btrfs-progs: Missing dependency util-linux (or rather, libblkid)

### ISSUE THREAD

**Issue by onodera-punpun** [kisslinux/community#645]

**Comment by aicsx** [comment]
-*blkid  
in order arch and crux consider this cycle:
e2fsprogs requires util-linux (libblkid)
btrfs-progs requires e2fsprogs

alpine treat it differently:
libblkid in "main" origin from util-linux
e2fsprogs and brtfs-progs requires libblkid.

We should decide how to treat it.

**Comment by dylanaraps** [comment]
The simplest solution is to just make btrfs-progs depend on util-linux.

**Comment by aicsx** [comment]
Ok, i change depends and bump at release 5.6 in next PR. I think for now it's can close.

**Comment by dylanaraps** [comment]
This has been fixed. Thanks all.
