### ISSUE TITLE
mpd: build fails due to undefined references

### ISSUE THREAD

**Issue by trbednarzyk** [kisslinux/community#647]
Like the title says, I am unable to build mpd (both the current community 0.21.21 version and the new 0.21.22 version in the pull request). Here's the actual error given for 0.21.21, though I get the same error for 0.21.22:
```
/usr/lib/gcc/x86_64-pc-linux-musl/9.3.0/../../../../x86_64-pc-linux-musl/bin/ld: /usr/lib/libavcodec.so: undefined reference to `lzma_code@XZ_5.0'
/usr/lib/gcc/x86_64-pc-linux-musl/9.3.0/../../../../x86_64-pc-linux-musl/bin/ld: /usr/lib/libavcodec.so: undefined reference to `lzma_stream_decoder@XZ_5.0'
/usr/lib/gcc/x86_64-pc-linux-musl/9.3.0/../../../../x86_64-pc-linux-musl/bin/ld: /usr/lib/libavcodec.so: undefined reference to `lzma_end@XZ_5.0'
```

Here is the complete build output: [out.txt](https://github.com/kisslinux/community/files/4447011/out.txt)

**Comment by trbednarzyk** [comment]
Strangely, this is only occurring on my desktop. I was just now able to successfully install mpd on my laptop.

**Comment by cemkeylan** [comment]
`libavcodec.so` belongs to `ffmpeg`, and `lzma` belongs to `xz`. I had this issue as well, and solved it by rebuilding `xz`, rebuilding `ffmpeg` with the new `xz`, and then building `mpd`.

**Comment by trbednarzyk** [comment]
Thank you, that worked!

**Comment by cemkeylan** [comment]
Great!
