### ISSUE TITLE
qemu: unable to passthrough host USB device

### ISSUE THREAD

**Issue by eudaldgr** [kisslinux/community#651]
After installing `libusb` package, for the obvious. `qemu` didn't start with this error message.
```
Error loading shared library libintl.so.8: No such file or directory 
(needed by /usr/lib/libgpg-error.so.0)
```
without the usb option it works properly.
@jedavies-dev

**Comment by jedavies-dev** [comment]
Tested locally by installing libusb and then rebuilding qemu - worked OK for me.

Some thoughts:
 - Looking at the error you got, doesn't libintl.so come from gettext?  Did you have gettext installed at some point recently?
 - What do you see when you do this:  ldd /usr/lib/libgpg-error.so.0
 - Can you run /usr/bin/gpg-error OK?   Also see ldd /usr/bin/gpg-error

**Comment by eudaldgr** [comment]
1.- Yes i installed `gettext` recently, now it's removed.
2.-
```
        ldd (0x7fec53cc7000)
Error loading shared library libintl.so.8: No such file or directory (needed by /usr/lib/libgpg-error.so.0)
        libc.so => ldd (0x7fec53cc7000)
```
3.-
```
Error loading shared library libintl.so.8: No such file or directory (needed by /usr/bin/gpg-error)
Error loading shared library libintl.so.8: No such file or directory (needed by /lib/libgpg-error.so.0)
```

**Comment by jedavies-dev** [comment]
I'd guess that you built libgpg-error while gettext was installed and it was therefore linked to libintl.  Now gettext is no longer present, the program cannot start.

Try rebuilding libgpg-error and see if that resolves it.  You may have other packages which are also linked to gettext and could cause problems, so anything else showing this kind of error should be rebuilt also.

**Comment by eudaldgr** [comment]
Thanks, it's a stupid issue.
