### ISSUE TITLE
libXslt: fails to build

### ISSUE THREAD

**Issue by eudaldgr** [kisslinux/community#667]
@cemkeylan 

`kiss b libXslt`
```
grep: /usr/lib/libintl.la: No such file or directory
sed: /usr/lib/libintl.la: No such file or directory
libtool:   error: '/usr/lib/libintl.la' is not a valid libtool archive
make[2]: *** [Makefile:499: libexslt.la] Error 1
make[2]: Leaving directory '/home/eudaldgr/.cache/kiss/build-2496/libXslt/libexslt'
make[1]: *** [Makefile:615: all-recursive] Error 1
make[1]: Leaving directory '/home/eudaldgr/.cache/kiss/build-2496/libXslt'
make: *** [Makefile:441: all] Error 2
-> libXslt Build failed
```
[Complete log](https://termbin.com/ptvm)

**Comment by cemkeylan** [comment]
That's weird, I don't have `/usr/lib/libintl.la` on my system, yet I don't have build issues.

It might be that one of your libraries are broken, because of an update, or removal of a package. Try to reinstall removed packages and rebuild the package.

I will get to this in a few hours, sorry for the delay.

**Comment by cemkeylan** [comment]
Okay, `libintl.a` is a `gettext` library. If you previosly installed it, that's why. I think that you may need to rebuild `libtool`, because it may be the issue here.

**Comment by cemkeylan** [comment]
Also libXslt links itself to these packages if they exist,

* libgcrypt
* libgpg-error
* xz
* zlib

So you may want to check them as well

**Comment by eudaldgr** [comment]
yeah, i know it's something related the `gettext` package, but the thing is that after remove it, i rebuild all my installed packages and the problem persists

**Comment by cemkeylan** [comment]
You can try something like this.

```sh
for lib in /usr/lib/*.so; do
    ldd $lib 2>/dev/null | grep -q libintl || continue
    printf '%s: depends on libintl\n' "$lib"
done
```

**Comment by eudaldgr** [comment]
There is no output for this.

**Comment by konimex** [comment]
Since libintl *doesn't* exist and (iirc) ldd will throw an error to stderr. Perhaps you need to do `2>&1` instead of `2>/dev/null`.

**Comment by cemkeylan** [comment]
Okay, then try

```sh
for lib in /usr/lib/*.so; do ldd $lib >/dev/null ; done
```

This will output all errors on your libraries

**Comment by eudaldgr** [comment]
[Output](https://termbin.com/y17r)

**Comment by cemkeylan** [comment]
I am unsure about this situation. I would advise rebuilding libxml2 and binutils, but I honestly don't know.

**Comment by eudaldgr** [comment]
I don't know why but when i packaged `surf` it was builded, the problem was happened when i'm trying to build `vimb`, and now i don't want it, but i think is solved and don't know why.

**Comment by dylanaraps** [comment]
This is an issue with your system and not the libXslt package. :+1:
