### ISSUE TITLE
Add xorriso to repo

### ISSUE THREAD

**Issue by scsijon** [kisslinux/community#67]
[quote]xorriso copies file objects from POSIX compliant filesystems into Rock Ridge enhanced ISO 9660 filesystems and allows session-wise manipulation of such filesystems. It can load the management information of existing ISO images and it writes the session results to optical media or to filesystem objects.
Vice versa xorriso is able to copy file objects out of ISO 9660 filesystems. [/quote]

I couldn't say it any better, so I didn't try.

url is https://www.gnu.org/software/xorriso/

Talk to Thomas Schmitt,  scdbackup@gmx.net. I'm sure he would help and support it and help you in adding it as he has with many others.

Oh, and it is both command line and gui capable.

**Comment by dylanaraps** [comment]
Transferred. :+1:

**Comment by dylanaraps** [comment]
Added thanks to #84.

**Comment by scsijon** [comment]
On 17/11/19 07:25, dylan wrote:
> Closed #67.
> 
Just a note that xorriso is also known as libisoburn (which contains it) 
so I don't know which name it should really be under. ?Do we need the 
full package for xorriso or the libisoburn version? Yes confusing I 
know, it's just how Thomas Schmitt did it back then, and both names are 
relevant. Maybe a note somewhere?

regards

**Comment by dylanaraps** [comment]
Repology lists it as `xorriso` as it seems to be named this way in all major distributions.

**Comment by scsijon** [comment]
On 17/11/19 11:05, dylan wrote:
> Repology lists it as `xorriso` as it seems to be named this way in all major distributions.
> 
  No worries, I was just mentioning what Thomas had said in his email to 
us in T2 a few weeks ago when it was queeried by me. I'm cc'ing him in 
case he wants to reply to this list also.

To quote him
-----------------
My apologies for creating this ambiguity. The reason lies back in 2008,
when the first packager preferred the 2-in-1 source tarball, with the
reasoning that this worked well with cdrskin in the libburn tarball.
Because of the difficulty to install .so without breaking the local
package management, i always had a xorriso-standalone tarball, which in
2010 became GNU xorriso.

Distros which use both, libisoburn and xorriso tarballs, most probably
have a duplication. Who installs libisoburn should also install its
xorriso binary. The size difference is substantial.

But as soon as the user needs a newer xorriso than provided by the 
distro, it is time for GNU xorriso from source. It does not need 
installation to places like /usr/bin, but can be run at the place were 
it was built.
Therefore grub-mkrescue has an option --xorriso= by which one can use 
such a built but not installed xorriso.

Both xorrisos get composed from the same sources. If linked with the 
same set of optional libraries (like zlib) they are supposed to behave
identically.


Have a nice day

Thomas
-----------------------------
End of quote.

regards
scsijon
