### ISSUE TITLE
giblib: bad source URL

### ISSUE THREAD

**Issue by trbednarzyk** [kisslinux/community#709]
The URL to `giblib-1.2.4.tar.gz` is bad, causing a checksum mismatch when running `kiss b giblib` and the inability to untar the downloaded file.
The proper URL for the file is: `https://github.com/aicsx/kiss-repo/raw/master/giblib/giblib-1.2.4.tar.gz`

@aicsx

**Comment by aicsx** [comment]
tomorrow i verify, thank you. it is not excluded that he forgot to update checksums by mistake

**Comment by aicsx** [comment]
It's in PR https://github.com/kisslinux/community/pull/711 .
there was actually a checksums error, but I took the opportunity to take advantage of the switch suggestion in / raw / . Thank you trbednarzyk.

**Comment by trbednarzyk** [comment]
Yes, there was a checksums error but at least on my system simply running `kiss c giblib` did not work. After running that, `kiss b giblib` would print the following error: 
```
gzip: skipping: <stdin> unrecognized format
tar: short read
!> giblib Couldn't extract giblib-1.2.4.tar.gz
```

Anyway, the source is good now but I'll be opening another issue as there is still a checksums error.
