### ISSUE TITLE
webkit2gtk: full fledged build

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/community#732]
I would like to have a alternative version to the existing webkit2gtk which is able to play videos.
Looking at the build there is pretty much everything disabled. Are there security concerns?
I have allready tried with the following but no succes to play videos on eg [media.cc](https://media.ccc.de/v/jhremote20-3004-antisurveillancerouter).  
Youtube errors with no available html5 support but that might be an issue on its own.
@cemkeylan do you have allready tested this?
```
cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_INSTALL_DIR=/usr/lib \
    -DPORT=GTK \
    -DCMAKE_SKIP_RPATH=ON \
    -DENABLE_BUBBLEWRAP_SANDBOX=OFF \
    -DENABLE_SAMPLING_PROFILER=OFF \
    -DENABLE_GEOLOCATION=OFF \
    -DENABLE_GLES2=ON \
    -DENABLE_INTL=OFF \
    -DENABLE_INTROSPECTION=OFF \
    -DENABLE_MINIBROWSER=OFF \
    -DENABLE_OPENGL=ON \
    -DENABLE_SPELLCHECK=OFF \
    -DENABLE_VIDEO=ON \
    -DENABLE_WEBGL=OFF \
    -DENABLE_WEB_AUDIO=ON \
    -DUSE_LIBHYPHEN=OFF \
    -DUSE_LIBNOTIFY=OFF \
    -DUSE_LIBSECRET=OFF \
    -DUSE_OPENJPEG=ON \
    -DUSE_WOFF2=OFF \
    -DUSE_WPE_RENDERER=OFF \
    -DENABLE_WEB_CRYPTO=OFF \
    -DENABLE_MEDIASOURCE=ON \
    -Wno-dev
```
Aditionally I have installed:
```
gst-plugins-bad 1.16.2 1
gst-plugins-base 1.16.2 1
gstreamer 1.16.2 1
```

**Comment by cemkeylan** [comment]
Yeah, this was intentional as we wanted to keep the dependencies minimum. Youtube gives that error because video streaming is disabled. I personally use webkitgtk with surf, and I use mpv for media playback.

Surf has a patch to open the current video with mpv, if you would be interested in that.

If you have gstreamer libraries, you can enable video streaming with `kiss-fork` and `kiss-link`.

I think adding the gstreamer libraries as dependencies is not necessary, as it is not a must feature, but I can add and maintain them if others don't agree.

What do you think @dylanaraps ? I would also like to get feedback from other webkit users.

**Comment by sdsddsd1** [comment]
In mpv: Yes I know about it and use it but sometimes I also like just to click (: .
Wouldn´t it be possible to add webkit2gtk-fullfledged and use kiss alternatives?

**Comment by dylanaraps** [comment]
> Wouldn´t it be possible to add webkit2gtk-fullfledged and use kiss alternatives?

Yeah. Though there's no need if the user only installs one instance of webkit2gtk.

**Comment by dylanaraps** [comment]
We could set them (gst-whatever) to `auto` (in configure) so that webkit2gtk builds with them if installed and without if not. A simple `post-install` message can they be added to inform users.

**Comment by cemkeylan** [comment]
Setting to AUTO requires them to exist, and doesn't build without gstreamer

**Comment by cemkeylan** [comment]
I can create a new version where it just enables video and audio support

**Comment by sdsddsd1** [comment]
I think the vanilla webkit2gtk doesnt show preview images on e.g reddit. Since I  enabled `openjpeg`  they do.

**Comment by cemkeylan** [comment]
No, I haven't had any issues with images without openjpeg.

**Comment by sdsddsd1** [comment]
@cemkeylan Ok you are right, nvm.

**Comment by cemkeylan** [comment]
Okay, so I am trying with `OPENGL=OFF`. IIRC that is not necessary for video/audio playback. I will report back when the build is over (around half an hour).

**Comment by cemkeylan** [comment]
Nope, it still can't stream audio or video. Here is the build

```sh
#!/bin/sh -e

patch -p1 < fix-musl.patch

# Remove gettext requirement.
sed -i 's/ngettext/printf/g' Tools/MiniBrowser/gtk/BrowserDownloadsBar.c
sed -i '/po_files \*\.po/d'  Source/WebCore/platform/gtk/po/CMakeLists.txt
sed -i '/^GETTEXT_C/d'       Source/WebCore/platform/gtk/po/CMakeLists.txt

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_INSTALL_DIR=/usr/lib \
    -DPORT=GTK \
    -DCMAKE_SKIP_RPATH=ON \
    -DENABLE_BUBBLEWRAP_SANDBOX=OFF \
    -DENABLE_SAMPLING_PROFILER=OFF \
    -DENABLE_GEOLOCATION=OFF \
    -DENABLE_GLES2=ON \
    -DENABLE_INTL=OFF \
    -DENABLE_INTROSPECTION=OFF \
    -DENABLE_MINIBROWSER=OFF \
    -DENABLE_OPENGL=OFF \
    -DENABLE_SPELLCHECK=OFF \
    -DENABLE_VIDEO=ON \
    -DENABLE_WEBGL=OFF \
    -DENABLE_WEB_AUDIO=ON \
    -DUSE_LIBHYPHEN=OFF \
    -DUSE_LIBNOTIFY=OFF \
    -DUSE_LIBSECRET=OFF \
    -DUSE_OPENJPEG=ON \
    -DUSE_WOFF2=OFF \
    -DUSE_WPE_RENDERER=OFF \
    -DENABLE_WEB_CRYPTO=OFF \
    -DENABLE_MEDIASOURCE=ON \
    -Wno-dev

cmake --build   build
cmake --install build
```

I have installed `gstreamer`, `gst-plugins-base` and `gst-plugins-bad`

**Comment by sdsddsd1** [comment]
I have pushed my gstreamer builds to my [repo](https://github.com/sdsddsd1/kiss-s3d4/tree/master/personal-repo). I just let them autoconfigure.

**Comment by sdsddsd1** [comment]
Got it. Check my repo for the aditional gst* . We may find out if all are needed. This time no dependsfile.

**Comment by sdsddsd1** [comment]
I have sucessfully working youtube and a test .mp4 video with
```
gstreamer
gst-plugins-base
gst-plugins-good
gst-plugins-bad
```

**Comment by cemkeylan** [comment]
Great! I'm sorry for not being attentive enough. I will
build and try them out now.

Also, I may have an idea for keeping this in the same
package, but I need input on this from @dylanaraps .

Here is the gist, maybe we could check if the package is
installed in the build file like this, and enable options
based on that. So it could look like this.

``` sh
#!/bin/sh -e

# Check if gst plugins are available
kiss l \
    gstreamer \
    gst-plugins-base \
    gst-plugins-good \
    gst-plugins-bad &&
    streaming=ON
    
cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    ...
    -DENABLE_VIDEO=${streaming:-OFF}
    -DENABLE_MEDIASOURCE=${streaming:-OFF}
    -Wno-dev
    
cmake --build build
cmake --install build
    

```

What do you think about this?

**Comment by cemkeylan** [comment]
Yeah, it is working with me as well with the addition of `gst-plugins-good`! ~I will test it for an hour to make sure there aren't any issues.~ Okay, I already have quite a lot of them :D

- Youtube seems to be working well
- Invidious says `No compatible source was found for this media.`
- Soundcloud has glitchy audio. It starts as expected for a few seconds, then it starts making weird noises and gets stuck in a buffering view without any audio.

A thing that I noticed is that you have added a `libflac` dependency to `gst-plugins-good`, which is not in the repositories, but it is not needed.

**Comment by sdsddsd1** [comment]
I can confirm your issues aswell.  
Installing `gst-plugins-ugly` and `gst-libav fixes` all. No invidious without gst-libav.  
So we might just accept that all are needed (:

**Comment by cemkeylan** [comment]
Yeah, invidious and reddit does work now, but soundcloud still only streams the first second of the song and hangs there.

**Comment by dylanaraps** [comment]
I suggest a jumbo `gst-plugins` package which contains all of them. Makes it easier to wrap your head around the naming scheme and what is needed for what.

@cemkeylan Anything outputted to the terminal?

**Comment by cemkeylan** [comment]
No, nothing is outputted to the terminal.

**Comment by cemkeylan** [comment]
gst-plugins package would make sense, I will package something like that. What do you think about the check we can do in the webkit2gtk package?

**Comment by dylanaraps** [comment]
That's fine by me. :+1:
