### ISSUE TITLE
readline: build with --with-curses option

### ISSUE THREAD

**Issue by periish** [kisslinux/community#734]
Any package that tries to link to readline will throw out errors along the lines of https://termbin.com/i3tq. @a-schaefers

**Comment by dylanaraps** [comment]
Note: This may not solve the issue. Some further digging may be required. From what I can understand, the above error will occur with everything that tries to link to readline.

**Comment by dylanaraps** [comment]
This *should* fix the issue and I'd like to get confirmation from @periish before we go ahead with it.

```sh
#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"

for patch in readline80-00*; do
    patch -p0 < "$patch"
done

./configure \
    --prefix=/usr

make SHLIB_LIBS=-lncurses
make DESTDIR="$1" install
```

**Comment by periish** [comment]
Works now. Issue has been fixed.

**Comment by periish** [comment]
Oops, sorry. Misclick.
