### ISSUE TITLE
wget: error: HTTP/1.1 307 Temporary Redirect

### ISSUE THREAD

**Issue by tristelune1** [kisslinux/community#74]
Hello, I'm trying to download `gimp` to build it. Here is the download link:

[gimp download](https://download.gimp.org/mirror/pub/gimp/v2.10/gimp-2.10.14.tar.bz2)

In a browser it works without problem. When I download `gimp` with `kiss`, I get the error:

````
wget: server returned error: HTTP/1.1 307 Temporary Redirect
!> gimp Failed to download https://download.gimp.org/mirror/pub/gimp/v2.10/gimp-2.10.14.tar.bz2
````

If I understood right, `wget` from `busybox` can't follow a redirection or at least this kind. Is it right ? Do you have a workaround ?

**Comment by dylanaraps** [comment]
I followed the redirection using `curl`. You can swap the upstream URL to: 

```
https://www.mirrorservice.org/sites/ftp.gimp.org/pub/gimp/v2.10/gimp-2.10.14.
tar.bz2
```

(At least until the original URL doesn't redirect here).
