### ISSUE TITLE
Packaging gimp

### ISSUE THREAD

**Issue by tristelune1** [kisslinux/community#75]
Hello,

I'm trying to package `gimp`. For the moment I have the problem with the `intltool` dependency. I don't know `intltool`, from what I can see it's use for the translation. If I understand right, if we get ride of `intltool` gimp will be only in english. Right ? 

I only know some files in `po` directories or ending with `po` are used for translation. So do I have to get ride of:

- all calls to `intltool` ? 
- delete `po` files or `po` directory ? 

So I can know in which direction I have to investigate. I tried to package like sabotage, but it didn't work.

**Comment by dylanaraps** [comment]
Does `--disable-nls` fix the issue? I'd need to see exact terminal output from the build to help any further.

**Comment by tristelune1** [comment]
Configure:

````
./configure \
    --prefix=/usr \
    --libexecdir=/usr/bin \
    --disable-altivec \
    --disable-static \
    --disable-python \
    --disable-nls \
    --without-lcms \
    --without-webkit
````

Output of configure: [terminal output](http://pastebin.fr/59211)

So it doesn't fix the issue.

**Comment by dylanaraps** [comment]
```sh
checking whether NLS is requested... no
./configure: line 1: intltool-update: not found
checking for intltool >= 0.40.1...  found
configure: error: Your intltool is too old.  You need intltool 0.40.1 or later.
```

This looks to me like broken `nls` (`gettext`, `intltool` etc) detection.

**Comment by tristelune1** [comment]
I deleted a lot of lines in `configure` and I was able to get ride of this problem I think. Is it possible, that the problem is here ? 

````
######################
# Internationalisation
######################


  { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether NLS is requested" >&5
$as_echo_n "checking whether NLS is requested... " >&6; }
    # Check whether --enable-nls was given.
if test "${enable_nls+set}" = set; then :
  enableval=$enable_nls; USE_NLS=$enableval
else
  USE_NLS=yes
fi

  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $USE_NLS" >&5
$as_echo "$USE_NLS" >&6; }




case "$am__api_version" in
    1.01234)
        as_fn_error $? "Automake 1.5 or newer is required to use intltool" "$LINENO" 5
    ;;
    *)
    ;;
esac

INTLTOOL_REQUIRED_VERSION_AS_INT=`echo 0.40.1 | awk -F. '{ print $ 1 * 1000 + $ 2 * 100 + $ 3; }'`
INTLTOOL_APPLIED_VERSION=`intltool-update --version | head -1 | cut -d" " -f3`
INTLTOOL_APPLIED_VERSION_AS_INT=`echo $INTLTOOL_APPLIED_VERSION | awk -F. '{ print $ 1 * 1000 + $ 2 * 100 + $ 3; }'`
if test -n "0.40.1"; then
    { $as_echo "$as_me:${as_lineno-$LINENO}: checking for intltool >= 0.40.1" >&5
$as_echo_n "checking for intltool >= 0.40.1... " >&6; }
    { $as_echo "$as_me:${as_lineno-$LINENO}: result: $INTLTOOL_APPLIED_VERSION found" >&5
$as_echo "$INTLTOOL_APPLIED_VERSION found" >&6; }
    test "$INTLTOOL_APPLIED_VERSION_AS_INT" -ge "$INTLTOOL_REQUIRED_VERSION_AS_INT" ||
        as_fn_error $? "Your intltool is too old.  You need intltool 0.40.1 or later." "$LINENO" 5
fi
````
I'm not sure, but it seems `nls` is not taken into account, the version of `intltool` is checked. I will try to patch it and then to build it.

**Comment by tristelune1** [comment]
Packaging for Gimp done! Now I have to check my builds before creatings some pull requests.

**Comment by muevoid** [comment]
@Vouivre Did you ever upload the package files anywhere specifically the patch? I am having no luck getting gimp to compile.

**Comment by Vouivre** [comment]
Hello, now it's done: https://github.com/Vouivre/kiss-repository/tree/master/packages

Keep in mind the following:

- I forgot perhaps to upload some dependencies which are not packaged for Kiss
- I can't submit it on community. You will have to manually install some dependencies, because I didn't check the `depends` file
- I don't have the latest version, it's 2.10.14
- I removed `glib-networking`. Now it's packaged in KISS, but as I understood it, it's only for the documentation, so I don't need it.
- at start, there will be an error. If I remember correctly, a plugin can't be load (pagecurl or something else). Just delete it. 

Just tell me if you are interested to test my package when it will be done. But for the moment I don't have enough time. 

I let you open an issue in my repository if it doesn't work for you.
