### ISSUE TITLE
Zathura missing runtime dependency on file

### ISSUE THREAD

**Issue by DevonMorris** [kisslinux/community#759]
I installed `zathura` and `zathura-pdf-mupdf` and then tried to open a pdf. See the following output

```bash
devon@KISS:~/Downloads|→  zathura Cpp_smart_pointers_ebook.pdf
warning: failed to execute command: Failed to execute child process
error: Could not determine file type.
```

Upon installing `file` I was able to open the pdf.

@Vouivre @ioraff

**Comment by Vouivre** [comment]
Thank you, I missed this dependency. I have created a PR (https://github.com/kisslinux/community/pull/764)
