### ISSUE TITLE
cups-filters: unable to build

### ISSUE THREAD

**Issue by eudaldgr** [kisslinux/community#794]
[log](https://termbin.com/3uy7)
```
checking for ""... no
configure: error: Requested font file is missing. Please install a package providing it.
-> cups-filters Build failed
```
@Vouivre

**Comment by dylanaraps** [comment]
The cups-filters package seems to depend on a specific font: https://github.com/OpenPrinting/cups-filters/blob/master/configure.ac#L787

Looks like we need to add `dejavu-ttf` to depends.

**Comment by dylanaraps** [comment]
OH! It's only needed for tests. We can disable them.

**Comment by eudaldgr** [comment]
Thanks!

**Comment by dylanaraps** [comment]
Try adding: 

```sh

# Disable stupid check for TTF font.
sed -i 's/as_fn_error.*Requested font/: "/' configure
```

before `./configure`.

**Comment by eudaldgr** [comment]
Error: [log](https://termbin.com/oxwt)

**Comment by dylanaraps** [comment]
Your error exactly:

```sh
mkdir: can't create directory '/home/eudaldgr/.cache/kiss/pkg-28405/cups-filters/usr/lib/cups/filter': File exists
make[3]: *** [Makefile:3073: install-pkgfilterSCRIPTS] Error 1
make[3]: *** Waiting for unfinished jobs....```

This is very odd.

**Comment by eudaldgr** [comment]
Yeah, and on the build pkg process, that's possible, a previous file that exist inside the package?

**Comment by Vouivre** [comment]
I think I missed it, sorry. I have tested this package on a chroot and it compiled without problems. But I had created of package for the `dejavu` fonts and it was available in that chroot. I have cleaned my chroot and will test again. 

@dylanaraps : is it not possible to disable the tests without a patch ? I'm rebuilding `cups-filters` and I will only be able to check tomorrow.

**Comment by Vouivre** [comment]
PR https://github.com/kisslinux/community/pull/806 created. I tried with the `sed` command and it works. 

@dylanaraps : thank you for the fix!
@eudaldgr  I would simply delete the path `/home/eudaldgr/.cache/kiss/pkg-28405/`
