### ISSUE TITLE
rtorrent: broken after libressl bump

### ISSUE THREAD

**Issue by eudaldgr** [kisslinux/community#819]
With the last `libressl` bump, `rtorrent` search for `libssl.so.47` & `libcrypto.so.45` and there is a `libssl.so.48` & `libcrypto.so.46`
It can be solved with a simple `ln -sf ...` almost for me.
@jedavies-dev

**Comment by eudaldgr** [comment]
https://github.com/kisslinux/community/issues/656#issuecomment-629761446

**Comment by dylanaraps** [comment]
You just need to rebuild `rtorrent`. Looks like another package not bumped for the release (otherwise this would have automatically happened). Closing this as it isn't a bug per se. 

@jedavies-dev Simply send a PR bumping the second field of the version file. No rush on this.

**Comment by eudaldgr** [comment]
I can't rebuild `rtorrent`: [log](https://termbin.com/129u)

**Comment by dylanaraps** [comment]
It looks like you need to rebuild `libtorrent` and then `rtorrent`. @jedavies-dev

**Comment by eudaldgr** [comment]
Thanks
