### ISSUE TITLE
Apply sbase tar patch so that _tar() can be removed from the package manager

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#823]
Adding this patch (https://patch-diff.githubusercontent.com/raw/michaelforney/sbase/pull/4.patch) from @E5ten will allow us to drop the `_tar()` function from the package manager. This tar implementation is the only known one to not support `-args`. This patch brings it in line with every other tar implementation we're aware of.

This patch has been submitted upstream (and to Michael Forney's mirror) though the latter depends on comments by the former. 

Upstream: https://lists.suckless.org/hackers/2005/17343.html
Michael Forney's repository: https://github.com/michaelforney/sbase/pull/4

We can speed up this process by simply using the patch until either "upstream" accepts it.

**Comment by E5ten** [comment]
@cemkeylan mentioning you because you maintain this package.
