### ISSUE TITLE
luajit: switch to moonjit

### ISSUE THREAD

**Issue by onodera-punpun** [kisslinux/community#846]
Alpine did so as well:

>*moonjit is now luajit*

>Our luajit package switched to the alive moonjit fork which has, among other things, s390x support and actual development.

https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.12.0#moonjit_is_now_luajit

**Comment by dylanaraps** [comment]
There are so many forks of LuaJIT... which one do we choose? Also, it looks like there's still active development in the original repository? https://github.com/LuaJIT/LuaJIT.

**Comment by onodera-punpun** [comment]
Oh I wongly thought it was a dead project...
