### ISSUE TITLE
sdl: missing dependency: linux-headers

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/community#851]
@alaughlin : sdl needs linux-headers to build.

**Comment by dylanaraps** [comment]
@sdsddsd1 This package is yours if you would like to adopt it. This issue has been open too long.

**Comment by sdsddsd1** [comment]
I will open a pull request.
`dosbox` is the only package in community which depends on `sdl`.
@jedavies-dev : is this sed command required for it?
