### ISSUE TITLE
 btrfs-progs: missing dependency: e2fsprogs

### ISSUE THREAD

**Issue by electimon** [kisslinux/community#866]
build error:
checking for EXT2FS... no
configure: error: Package requirements (ext2fs) were not met:

Package 'ext2fs', required by 'virtual:world', not found

**Comment by electimon** [comment]
@aicsx

**Comment by aicsx** [comment]
although it is not mentioned originally it seems to be correct. It will be added to the release of the next version (bump). Thanks for the tip.
