### ISSUE TITLE
SSL certificate expiration.

### ISSUE THREAD

**Issue by periish** [kisslinux/community#871]
The kernel mirrors have let their ssl certificates expire. If any of you have packages that use the kernel mirrors, they won't be able to be  built unless you update sources.

**Comment by dylanaraps** [comment]
Packages potentially affected:

```
community/btrfs-progs/sources:https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v5.6.tar.xz
community/cryptsetup/sources:https://www.kernel.org/pub/linux/utils/cryptsetup/v2.3/cryptsetup-2.3.2.tar.xz
community/ethtool/sources:https://mirrors.edge.kernel.org/pub/software/network/ethtool/ethtool-5.6.tar.xz
community/iproute2/sources:https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-5.6.0.tar.xz
community/keyutils/sources:https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/keyutils.git/snapshot/keyutils-1.6.1.tar.gz
community/kmod/sources:https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-27.tar.xz
community/libcap/sources:https://kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.34.tar.xz
community/man-pages-posix/sources:https://mirrors.edge.kernel.org/pub/linux/docs/man-pages/man-pages-posix/man-pages-posix-2013-a.tar.xz
community/man-pages/sources:https://mirrors.edge.kernel.org/pub/linux/docs/man-pages/man-pages-5.06.tar.xz
community/pciutils/sources:https://www.kernel.org/pub/software/utils/pciutils/pciutils-3.6.4.tar.gz
community/uemacs/sources:git+https://git.kernel.org/pub/scm/editors/uemacs/uemacs.git
community/usbutils/sources:https://kernel.org/pub/linux/utils/usb/usbutils/usbutils-012.tar.xz
```

**Comment by aicsx** [comment]
Yes, problems. 
in kiss command, curl error: 
curl (60) SSL certificate problem: certificate has expired

More details here: https://curl.haxx.se/docs/sslcertes.html

**Comment by cemkeylan** [comment]
ueamcs isn't affected. This is an issue with CertAuth as a whole, meaning other vendors outside of kernel.org is affected. gmplib.org (gcc/gmp) seems to be down as well.

**Comment by cemkeylan** [comment]
This isn't an issue of kernel.org forgetting to renew the certificates, since their expiration dates are not even near. This is a CA issue [affecting other hosts as well](https://status.gandi.net/incidents/026k81gp3vmk). https://kernel.org seems to have solved this issue (the CA issued a new signing key).

https://gmplib.org is still down (which is required in gcc).

**Comment by aicsx** [comment]
> This isn't an issue of kernel.org forgetting to renew the certificates, since their expiration dates are not even near. This is a CA issue [affecting other hosts as well](https://status.gandi.net/incidents/026k81gp3vmk). https://kernel.org seems to have solved this issue (the CA issued a new signing key).
> 
> https://gmplib.org is still down (which is required in gcc).

for now I solved it by manually downloading with wget the package in the .cache/kiss/source / gcc / gmp.extension

**Comment by cemkeylan** [comment]
I have changed the sources to point to the GNU ftp two days ago. It can be acquired from https://ftp.gnu.org/gnu/gmp/gmp-6.2.0.tar.xz as well.

**Comment by dylanaraps** [comment]
Fixed GCC, thanks.

**Comment by dylanaraps** [comment]
This should no longer be an issue. The latest libressl will also prevent this from happening again.
