### ISSUE TITLE
sdl2: Cannot build with dash

### ISSUE THREAD

**Issue by Admicos** [kisslinux/community#872]
sdl2 cannot build when /usr/bin/sh is set to dash (`kiss a dash /usr/bin/sh`)

This issue is already reported upstream at https://bugzilla.libsdl.org/show_bug.cgi?id=4261, but a workaround (like forcing busybox sh) or warning could be nice.

**Comment by sdsddsd1** [comment]
I think everything with an automation to use another sh shell is to complicated  and error prone.
I will display a simple warning at the beginning of the build. 
At least at the second attempt it should be visible what has happened.

**Comment by dylanaraps** [comment]
The dash issue has been fixed upstream: https://git.kernel.org/pub/scm/utils/dash/dash.git/commit/?id=e8e29001ad1cdeb68a5c617db149830e676c32c8

Bug report: https://www.mail-archive.com/dash@vger.kernel.org/msg01935.html

**Comment by dylanaraps** [comment]
Once @a-schaefers updates dash, this should be fixed.
