### ISSUE TITLE
lcms2: Change name to lcms

### ISSUE THREAD

**Issue by IslandAlpha** [kisslinux/community#902]
LCMS version 1 is not used by any packages and is not packaged, therefore the 2 is unnecessary.

I'm not used to changing package names; my plan is to create pull requests for the packages which depend on lcms2 so Dylan can commit them all at once.

- [x] openjpeg2 @IslandAlpha 
- [ ] cups-filters @Vouivre 
- [x] gst-plugins @cemkeylan

**Comment by dylanaraps** [comment]
You will need to wait for each maintainer to submit pull requests. :+1:

**Comment by dylanaraps** [comment]
Thanks all. :+1:
