### ISSUE TITLE
Sane: use scanner in KISS

### ISSUE THREAD

**Issue by Vouivre** [kisslinux/community#936]
Hello,

I need to build `sane` to use my scanner. After building it, the size is 20Mb. If I build it only for my scanner, I can shrink the package size to less than 1 Mb. For me it would be enough.

Is somebody interested with this package ? If nobody is interested by this package at the moment, I think it would be a good point to have it in community for some users later. I could maintain this package. If it's not needed, I will only compile it locally. 

I wait for your feedbacks.

**Comment by konimex** [comment]
You can post the `build` file here, if someone's interested. If no one's interested *now* but someone is interested *later*, they can refer to this issue.

**Comment by Vouivre** [comment]
Ok, so I will finish this package and I will refer to it on my own repository. I have opened an issue in `sane`. When it's resolved, I will make my `build` file available.

**Comment by Vouivre** [comment]
The issue I had with `sane` has been fixed upstream. After thinking about it, I find it easier for a new user to find `sane` in community than searching in the issues. I'm not sure I would search in the issues. So I have created a PR https://github.com/kisslinux/community/pull/948. 

Thank you for your feedback!
