### ISSUE TITLE
curlpp: depends fix

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/community#937]
@djt3 Cmake is just a make dependency for curlpp. [Arch](https://aur.archlinux.org/packages/libcurlpp/) [Alpine](https://git.alpinelinux.org/aports/tree/testing/curlpp/APKBUILD)

`depends`
cmake make
curl

**Comment by djt3** [comment]
thanks for letting me know, it looks like i also forgot to add cmake as a dependency for tuitube
