### ISSUE TITLE
qemu 5.0.0 2 build error

### ISSUE THREAD

**Issue by xzcvczx** [kisslinux/community#964]
@jedavies-dev 

ERROR: sizeof(size_t) doesn't match GLIB_SIZEOF_SIZE_T.
       You probably need to set PKG_CONFIG_LIBDIR
       to point to the right pkg-config files for your
       build target

[qemu-2020-06-27-13:14-2408.txt](https://github.com/kisslinux/community/files/4839860/qemu-2020-06-27-13.14-2408.txt)

had 5.0.0 1 installed with no problems, issue confirmed by micr0

**Comment by jedavies-dev** [comment]
Interesting - just tried rebuilding this and it works OK for me on my normal KISS installation.  Also tried this from a clean chroot (starting from the release tarball, add community repo, do "kiss b qemu").  Did this on powerpc64le and x86_64.  Package built OK in each case.

Have you updated glib recently?  There was a change to glib to enable building of static libraries that qemu now depends on.  Qemu would fail if glib isn't on the latest version for this reason.

**Comment by xzcvczx** [comment]
i was doing a kiss update when it failed to build so glib is up to date

**Comment by xzcvczx** [comment]
ok after rebuilding/installing glib it now works, closing
