### ISSUE TITLE
qt5 fails to build

### ISSUE THREAD

**Issue by quisys** [kisslinux/community#972]
Here are the [logs](http://sprunge.us/XlFTu7)

**Comment by dylanaraps** [comment]
You should really mention the maintainer of the package so that they can be notified.... @dilyn-corner 

Here's the actual error:
```
File '**' is not valid
make[2]: Entering directory '/home/finn/.cache/kiss/build-8715/qt5/src/widgets'
perl /home/finn/.cache/kiss/build-8715/qt5/mkspecs/features/data/unix/findclasslist.pl < QtWidgets.version.in > QtWidgets.version
g++ -pipe -O2 -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -dM -E -o .moc/moc_predefs.h ../../mkspecs/features/data/dummy.cpp
/home/finn/.cache/kiss/build-8715/qt5/src/widgets/uic_wrapper.sh dialogs/qfiledialog.ui -o .uic/ui_qfiledialog.h
File '**********************' is not valid
make[2]: *** [Makefile:78299: .uic/ui_qfiledialog.h] Error 1
make[2]: Leaving directory '/home/finn/.cache/kiss/build-8715/qt5/src/widgets'
make[1]: *** [Makefile:530: sub-widgets-make_first] Error 2
make[1]: *** Waiting for unfinished jobs....```

**Comment by dylanaraps** [comment]
There have been multiple discussions on this issue in IRC as well: https://freenode.logbot.info/?ch=kisslinux&q=is+not+valid

**Comment by dilyn-corner** [comment]
Based on all the conversations that have happened surrounding this bug (which is what I think it amounts to), we have a couple choices: 
1) Eliminate the UIC generation entirely (no thank you)
2) Distribute a pre-built file (I'd rather avoid hijacking the build system for a single file)
3) Have affected users install `icu`
4) Build qt5-base from source without `kiss`

3) is the easiest option, and the one I'm most comfortable with. 
4) is a good choice if you don't mind basically packaging `qt5` in the most manual way possible. It's really easy, just copy paste the commands `kiss` would run in generating the tarball, and then manually install it.

I've also had luck using an old version of `kiss` to build `qt5`. I have no idea why it would work. I have no idea how building with a shell script would fail at this one point, and not for every user who does it. It's strange.

**Comment by dylanaraps** [comment]
@dilyn-corner Do you by any chance have the version number of the working `kiss` package manager? I have a hunch as to what *may* be causing the issue though it's a stretch.

**Comment by quisys** [comment]
installing icu fixed it - maybe add it as a dep? just a thought, it looks like new kiss installs are affected

**Comment by dylanaraps** [comment]
Well, we're somewhat reluctant to go adding random dependencies to packages (in the general sense). I'd much rather we figure out what causes the build to fail and fix the problem at the source. Adding ICU as a dependency should be a last resort though I think this decision should be ultimately up to @dilyn-corner. I don't mind either way which solution is chosen.  :+1:

**Comment by dilyn-corner** [comment]
@dylanaraps as far as my own testing goes, building seems to work on kiss 1.9.0 and earlier. 

@quisys I have considered adding it as a dependency. Unfortunately it doesn't seem required outside of solving this bug, which as far as I'm aware is not effecting every user.
If it ends up that more people are having issues, I would probably make it a dependency. But that's mainly as a last resort. If Dylan can make a change (what that is I do not know) to stop this, that would be preferred.

**Comment by dylanaraps** [comment]
I fail to see how the package manager could have any involvement in this issue short of *possible* extraction issues. Are the permissions, access time, modified time, ownership, etc of the files identical between package manager versions? This is the only way for the package manager to have an affect on the build itself (in this case).

The reason I'm led here is that I've seen build failure due to incorrect `mtime` with GNU autotools based builds. This was caused by the files not retaining their tarball permissions. I've also had this happen due to an incorrect clock in the system. Build systems
can be finicky when it comes to these things so it wouldn't surprise me to see this build fail for the same reasons.

**Comment by dylanaraps** [comment]
It also interests me to find out *why* ICU being present avoids (or fixes(?)) this issue. It's rather odd.

**Comment by sdsddsd1** [comment]
I can also throw in that the binary packages provided [here](https://github.com/dilyn-corner/KISS-kde/releases/download/3.0.4/qt5.5.15.0-1.tar.gz) require icu to build related qt5-packages, altough `icu` is not listed as depends by kiss.

**Comment by dylanaraps** [comment]
@dilyn-corner If you think it's reasonable, we could also open an issue upstream about this. If only to gain better insight into what's going on. Trying to make sense of the qt5 sources is well.... difficult.

**Comment by dilyn-corner** [comment]
@dylanaraps I also have no clue how the package manager could screw it up - I built `qt5` exactly identically to how `kiss` would do it and had zero issues. 
I just cheched though and you might be onto something with date issues? At the very least, some of these files are dated for 12/31/1969 - which certainly isn't five minutes ago when I extracted the archive. Most notably, ever single file in src/tools/uic, which is where the problem would seem to originate from. 

@sdsddsd1 those binaries require `icu` because I'm the one building them and this is an issue that plagues me (: they only require `pcre2` becuase they're required for other KDE related packages. 

Opening an issue would be good, maybe. I never got any traction on any of the issues I've raised with them, but I can always file a bug report.
Considering their reticence to support libressl I doubt they'll have any interest in figuring out why a single file fails to properly generate/be parsed on a niche OS. Qt devs aren't fun to work with :X

**Comment by dylanaraps** [comment]
If you amend the dates (via `touch` possibly), does the build work?

**Comment by dylanaraps** [comment]
A lot of files seem to have incorrect permissions: ```
drwxr-xr-x    5 dylan    dylan          180 Jun 30 20:08 ./util/unicode
-rw-r--r--    1 dylan    dylan         2895 Jan  1  1970 ./util/unicode/README
drwxr-xr-x    3 dylan    dylan           60 Jun 30 20:08 ./util/unicode/codecs
drwxr-xr-x    2 dylan    dylan          120 Jun 30 20:08 ./util/unicode/codecs/big5
-rw-r--r--    1 dylan    dylan       350856 Jan  1  1970 ./util/unicode/codecs/big5/BIG5
-rw-r--r--    1 dylan    dylan           57 Jan  1  1970 ./util/unicode/codecs/big5/big5.pro
-rw-r--r--    1 dylan    dylan           97 Jan  1  1970 ./util/unicode/codecs/big5/big5.qrc
-rw-r--r--    1 dylan    dylan         4732 Jan  1  1970 ./util/unicode/codecs/big5/main.cpp
drwxr-xr-x    2 dylan    dylan          320 Jun 30 20:08 ./util/unicode/data
-rw-r--r--    1 dylan    dylan        37917 Jan  1  1970 ./util/unicode/data/ArabicShaping.txt
-rw-r--r--    1 dylan    dylan        26317 Jan  1  1970 ./util/unicode/data/BidiMirroring.txt
-rw-r--r--    1 dylan    dylan        10346 Jan  1  1970 ./util/unicode/data/Blocks.txt
-rw-r--r--    1 dylan    dylan        82810 Jan  1  1970 ./util/unicode/data/CaseFolding.txt
-rw-r--r--    1 dylan    dylan       122399 Jan  1  1970 ./util/unicode/data/DerivedAge.txt
-rw-r--r--    1 dylan    dylan       820928 Jan  1  1970 ./util/unicode/data/DerivedNormalizationProps.txt
-rw-r--r--    1 dylan    dylan        94780 Jan  1  1970 ./util/unicode/data/GraphemeBreakProperty.txt
-rw-r--r--    1 dylan    dylan       239738 Jan  1  1970 ./util/unicode/data/LineBreak.txt
-rw-r--r--    1 dylan    dylan         2116 Jan  1  1970 ./util/unicode/data/NormalizationCorrections.txt
-rw-r--r--    1 dylan    dylan       175811 Jan  1  1970 ./util/unicode/data/Scripts.txt
-rw-r--r--    1 dylan    dylan       206141 Jan  1  1970 ./util/unicode/data/SentenceBreakProperty.txt
-rw-r--r--    1 dylan    dylan        16830 Jan  1  1970 ./util/unicode/data/SpecialCasing.txt
-rw-r--r--    1 dylan    dylan      1851767 Jan  1  1970 ./util/unicode/data/UnicodeData.txt
-rw-r--r--    1 dylan    dylan       103240 Jan  1  1970 ./util/unicode/data/WordBreakProperty.txt
-rw-r--r--    1 dylan    dylan       111904 Jan  1  1970 ./util/unicode/main.cpp
-rw-r--r--    1 dylan    dylan           48 Jan  1  1970 ./util/unicode/unicode.pro
-rwxr-xr-x    1 dylan    dylan         2279 Jan  1  1970 ./util/unicode/writingSystems.sh
drwxr-xr-x    2 dylan    dylan           80 Jun 30 20:08 ./util/unicode/x11
-rw-r--r--    1 dylan    dylan         1595 Jan  1  1970 ./util/unicode/x11/encodings.in
-rwxr-xr-x    1 dylan    dylan         2830 Jan  1  1970 ./util/unicode/x11/makeencodings
drwxr-xr-x    2 dylan    dylan           80 Jun 30 20:08 ./util/x86simdgen
-rwxr-xr-x    1 dylan    dylan         5722 Jan  1  1970 ./util/x86simdgen/generate.pl
-rw-r--r--    1 dylan    dylan         1465 Jan  1  1970 ./util/x86simdgen/simd.txt
drwxr-xr-x    2 dylan    dylan          100 Jun 30 20:08 ./util/xkbdatagen
-rw-r--r--    1 dylan    dylan           46 Jan  1  1970 ./util/xkbdatagen/README
-rw-r--r--    1 dylan    dylan        18397 Jan  1  1970 ./util/xkbdatagen/main.cpp
-rw-r--r--    1 dylan    dylan           34 Jan  1  1970 ./util/xkbdatagen/xkbdatagen.pro
```

This is a small excerpt.

**Comment by dilyn-corner** [comment]
That is actually digusting. 

Is it too late to drop qt just out of spite and pettiness

**Comment by dylanaraps** [comment]
This issue seems to be in the tarball itself: 

```
-rw-r--r-- qt/qt    164300 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtDBus.5.10.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    164300 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtDBus.5.11.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    165694 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtDBus.5.12.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    191974 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtDBus.5.13.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    192963 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtDBus.5.14.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    135341 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtDBus.5.2.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    135588 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtDBus.5.3.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    136475 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtDBus.5.4.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    142968 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtDBus.5.6.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    151585 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtDBus.5.7.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    152223 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtDBus.5.8.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    152639 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtDBus.5.9.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    209244 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtGui.5.0.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    228456 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtGui.5.1.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    284852 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtGui.5.10.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    284852 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtGui.5.11.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    286246 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtGui.5.12.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    312245 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtGui.5.13.0.linux-gcc-amd64.txt
-rw-r--r-- qt/qt    313536 1970-01-01 02:00:00 qtbase-everywhere-src-5.15.0/tests/auto/bic/data/QtGui.5.14.0.linux-gcc-amd64.txt
```

**Comment by dylanaraps** [comment]
Huzzah! The dates are normal when using a different tar implementation. Busybox tar is to blame for the incorrect dates.

```
drwxr-xr-x  0 qt     qt          0 May 11 11:15 qtbase-everywhere-src-5.15.0/util/plugintest/
-rw-r--r--  0 qt     qt        188 May 11 11:15 qtbase-everywhere-src-5.15.0/util/plugintest/README
-rw-r--r--  0 qt     qt       1986 May 11 11:15 qtbase-everywhere-src-5.15.0/util/plugintest/main.cpp
-rw-r--r--  0 qt     qt         83 May 11 11:15 qtbase-everywhere-src-5.15.0/util/plugintest/plugintest.pro
drwxr-xr-x  0 qt     qt          0 May 11 11:15 qtbase-everywhere-src-5.15.0/util/qfloat16-tables/
-rw-r--r--  0 qt     qt       6165 May 11 11:15 qtbase-everywhere-src-5.15.0/util/qfloat16-tables/gen_qfloat16_tables.cpp
-rw-r--r--  0 qt     qt         45 May 11 11:15 qtbase-everywhere-src-5.15.0/util/qfloat16-tables/qfloat16-tables.pro
drwxr-xr-x  0 qt     qt          0 May 11 11:15 qtbase-everywhere-src-5.15.0/util/unicode/
-rw-r--r--  0 qt     qt       2895 May 11 11:15 qtbase-everywhere-src-5.15.0/util/unicode/README
drwxr-xr-x  0 qt     qt          0 May 11 11:15 qtbase-everywhere-src-5.15.0/util/unicode/codecs/
drwxr-xr-x  0 qt     qt          0 May 11 11:15 qtbase-everywhere-src-5.15.0/util/unicode/codecs/big5/
-rw-r--r--  0 qt     qt     350856 May 11 11:15 qtbase-everywhere-src-5.15.0/util/unicode/codecs/big5/BIG5
-rw-r--r--  0 qt     qt         57 May 11 11:15 qtbase-everywhere-src-5.15.0/util/unicode/codecs/big5/big5.pro
-rw-r--r--  0 qt     qt         97 May 11 11:15 qtbase-everywhere-src-5.15.0/util/unicode/codecs/big5/big5.qrc
-rw-r--r--  0 qt     qt       4732 May 11 11:15 qtbase-everywhere-src-5.15.0/util/unicode/codecs/big5/main.cpp
drwxr-xr-x  0 qt     qt          0 May 11 11:15 qtbase-everywhere-src-5.15.0/util/unicode/data/
-rw-r--r--  0 qt     qt      37917 May 11 11:15 qtbase-everywhere-src-5.15.0/util/unicode/data/ArabicShaping.t
```

**Comment by dilyn-corner** [comment]
Absolutely incredible. 
I'd rather not require `libarchive` to build `qt5` but a make dependency is better than a runtime dependency. 
Can you think of a way around this without doing that?

**Comment by dylanaraps** [comment]
We must first confirm that correct dates equate to a successful build. I'll also look into fixing busybox tar. :+1:

**Comment by dilyn-corner** [comment]
Trying it out now :+1:

**Comment by dylanaraps** [comment]
The permissions can also be retained by swapping to the `zip` source (http://download.qt.io/official_releases/qt/5.15/5.15.0/submodules/qtbase-everywhere-src-5.15.0.zip). Keep in mind that this drops everything into a subdirectory.

**Comment by dilyn-corner** [comment]
I can't even `./configure` in the zip source :thinking:

**Comment by dylanaraps** [comment]
Are you sure the `pwd` is correct. If using the `zip` you'll have to `cd` into the subdirectory first.

**Comment by dilyn-corner** [comment]
I'm talking about even outside the package manager.

**Comment by dylanaraps** [comment]
Let me see if I can reproduce...

**Comment by dylanaraps** [comment]
Oh god. The `.zip` file seems to be full of Windows line endings. Seems to be intended for use on Windows...

**Comment by quisys** [comment]
that's a yikes

**Comment by dylanaraps** [comment]
If you run `find . -type f -exec dos2unix {} +` prior to the build it should correct everything...

**Comment by dilyn-corner** [comment]
The .zip source also fails

**Comment by dylanaraps** [comment]
Have you tried with `libarchive` (`kiss a libarchive /usr/bin/tar`) and the `xz` source?

**Comment by dilyn-corner** [comment]
It also fails with libarchive tar.

**Comment by dylanaraps** [comment]
It looks like we'll have to add `icu` as a dependency sadly. Although this page seems to suggest that qt5 does not use icu? https://wiki.qt.io/Qt_5_ICU

**Comment by dilyn-corner** [comment]
"This plan has been abandoned" genius. 
I would be furious if there were undocumented options. 

Expect a pull-request some time this weekend either way!
