### ISSUE TITLE
xorriso out of date

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#99]
Ping @shizonic

**Comment by shizonic** [comment]
Pong @dylanaraps ?

**Comment by dylanaraps** [comment]
Oops, my bad. Apologies for the ping.... :sweat_smile: 

Ping @alaughlin. This is your package!

**Comment by shizonic** [comment]
Nothing to apologize @dylanaraps :)

**Comment by dylanaraps** [comment]
Ping @alaughlin

**Comment by alaughlin** [comment]
Hey sorry I’ve been offline for a while but I’ll get on this!

**Comment by dylanaraps** [comment]
Pushed the update myself. :+1:
